### ISSUE TITLE
setTokenLimit method required

### ISSUE THREAD

**Issue by apkelly** [splitwise/TokenAutoComplete#100]
Hi,

I'd like to limit the number of tokens allowed in the view, at the moment I override the onTokenAdded method and if the number is > than I allow I immediately call removeObject.

It'd be nice if there was a simple way to limit the number of tokens allowed in the view e.g. setTokenLimit, setMaxTokens.

Thanks,

Andy.

**Comment by mgod** [comment]
I feel like in most cases if you're using this view, you want the user to be able to enter as many tokens as they please. In your situation, I would probably disable the view after the max number of tokens is hit. Can you tell me a little more about your sue case?

**Comment by apkelly** [comment]
In my case we're entering suburb information which we're then going to search upon, we want to limit the number of suburbs to 10. At which point you can't enter any more, but you should still be able to remove suburbs if you want to change your query.

Being able to set a limit would disable text entry (swallow all keypreses except delete), so that new suburbs can't be added, but existing ones can be removed.

**Comment by jospint** [comment]
Hi @apkelly , I ran todayinto the same issue and found a way through.

```
private int tokenLimit = -1;

public void setTokenLimit(int tokenLimit){
        this.tokenLimit = tokenLimit;
}
```
And then you will have to modify those lines where the filter is set...

```
// Initialise the textfilter (listens for the splitchars)
        setFilters(new InputFilter[] {new InputFilter() {
            @Override
            public CharSequence filter(CharSequence source, int start, int end, Spanned dest, int dstart, int dend) {
                //Detect split characters, remove them and complete the current token instead
                if (tokenLimit != -1 && objects.size() == tokenLimit) {
                    return "";
                } else {
                    if (source.length() == 1) {
                        boolean isSplitChar = false;
                        for (char c : splitChar) isSplitChar = source.charAt(0) == c || isSplitChar;
                        if (isSplitChar) {
                            performCompletion();
                            return "";
                        }
                    }

                    //We need to not do anything when we would delete the prefix
                    if (dstart < prefix.length() && dend == prefix.length()) {
                        return prefix.substring(dstart, dend);
                    }
                    return null;
                }
            }
        }});
```

**Comment by mgod** [comment]
This feels like it would be a not great user experience to me, but I'm happy to merge this in! I'll include this in 1.3.2 when I wrap up a couple of other fixes, but until then, you can build your own jar as noted in the README.

**Comment by apkelly** [comment]
@jospint Thanks for the code snippet, I might add a new interface method for the listener on my local version to say onTokenLimitReached() so that I can catch the event in my code.

**Comment by jospint** [comment]
@apkelly You can actually take control of tokens added or deleted already through this interface

```javascript
public static interface TokenListener {
    public void onTokenAdded(Object token);
    public void onTokenRemoved(Object token);
}
```

**Comment by apkelly** [comment]
@jospint unfortunately those methods get called multiple times when restoring instance state. I'm using them currently to try and keep count of the tokens entered. Which is why when my state was being restore and I was seeing tokens added again I came to the conclusion that a set limit function was needed.

My comment above would have added an onTokenLimitReached() method to the interface you highlighted.

Looking forward to v1.3.2
