### ISSUE TITLE
1.3.x broke where 1.2.1 was working

### ISSUE THREAD

**Issue by anatolyrc** [splitwise/TokenAutoComplete#105]
We were using the 1.2.1 jar with our project, which was being built with Eclipse. This was working great, but after converting the project to Android Studio, and changing from the jar to referencing the latest aar from the online repository, tokenautocomplete started failing to replace the text with tokens, either when typed in, or selected from the autocomplete list. Going back to the 1.2.1 jar fixed it. (Tested on stock Nexus 7 with Android 4.4.4, among others.) Any ideas what's going on?

**Comment by mgod** [comment]
What are your minimum and target API versions?



—

**Comment by anatolyivasyuk** [comment]
Min 14, target 21. I am aware that the minimum for 1.3 is 15, but the code where this is used is only run on 16 and later anyway, and the testing was done on 19.

**Comment by mgod** [comment]
Hmmmm, 14 should be fine. I can probably actually officially support 14, but I don't have any way to test it. The big difference between 1.2.1 and 1.3.0 for this particular issue is that we no longer do a number of double checks on the text changing to make sure the callbacks go off. If you load the example project on that device, do you see the same issue or does it work correctly? I'm not able to reproduce this issue myself.

**Comment by hzsweers** [comment]
gradle dependency can't be used if your project's min is lower than the dependency. We had the same issue, and had to create a jar ourselves to support the lower version. If you'd be willing to consider supporting 14, that would be great. Can't think of any issues that would arise from that switch

**Comment by mgod** [comment]
I've gone ahead and bumped the min version down to 14.
