### ISSUE TITLE
Error inflating class com.tokenautocomplete.ContactsCompletionView

### ISSUE THREAD

**Issue by CapitanRedBeard** [splitwise/TokenAutoComplete#107]
Hey mgod,
I link the dependencie in my gradle file:

        compile "com.splitwise:tokenautocomplete:1.3.1@aar"

My fragments onCreateView looks like:

    View view = inflater.inflate(R.layout.fragment_tutor_setup, container, false);

        String[] strings = new String[]{"photoshop",""};

        adapter = new ArrayAdapter<String>(getActivity(), R.layout.fragment_tutor_setup, strings);

        completionView = (ContactsCompletionView)view.findViewById(R.id.searchView);
        completionView.setAdapter(adapter);

        if (savedInstanceState == null) {
            completionView.setPrefix("Skills: ");
        }
        return view;

And then I extend a ContactsCompletionView like so:

    public class ContactsCompletionView extends TokenCompleteTextView {
    public ContactsCompletionView(Context context) {
        super(context);
    }
    public ContactsCompletionView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }
    public ContactsCompletionView(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
    }
    @Override
    protected View getViewForObject(Object object) {
        String s = (String)object;

        LayoutInflater l = (LayoutInflater)getContext().getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
        LinearLayout view = (LinearLayout)l.inflate(R.layout.contact_token, (ViewGroup)ContactsCompletionView.this.getParent(), false);
        ((TextView)view.findViewById(R.id.name)).setText(s);

        return view;
    }
    @Override
    protected Object defaultObject(String completionText) {
        return completionText;
    }
}

And finally in my fragment_tutor_setup.xml:

    <com.tokenautocomplete.ContactsCompletionView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

The final error is:     

     android.view.InflateException: Binary XML file line #34: Error inflating class login.shogun.comet.halp.ContactsCompletionView

     

I know I have came across this problem before so at first rebuilt my project and invalidate the caches. If you would like me to post more code I would be more than happy too. I appreciate any time you give to help me out!

-Emmett

  [1]: https://github.com/splitwise/TokenAutoComplete

**Comment by mgod** [comment]
I'm sorry for the confusion! I can see where I need to tweak the docs. In your layout XML, you need to use ```login.shogun.comet.alp.ContactsCompletionView``` instead of ```com.tokenautocomplete.ContactsCompletionView``` or whatever your actual package path is.
