### ISSUE TITLE
Completion on hiting space button

### ISSUE THREAD

**Issue by TOMKHAN** [splitwise/TokenAutoComplete#108]
Hi.

I stumbled on your great library a few days ago. Since then, I've played with it and everything works just fine. But now, I'm curious. Is it possible to complete the token when user hits "space" button on keyboard, just like on the Gmail? As I see in your source of the library, handleDone() is only called at 
onEditorAction() and onKeyUp().

btw. thanks for the great work! :+1:

**Comment by TOMKHAN** [comment]
If you ever wandered how, go to the https://github.com/Style87/TokenAutoComplete and study what Style87 did.

For some reason, author of this library is not using "space" for finishing tokens. Even though, I thank him for saving me weeks of work.

**Comment by mgod** [comment]
@TOMKHAN I'm so sorry I missed this issue when you opened it! I'm not sure why github didn't email me. You should also be able to use setSplitChar in the main version to set an array of characters you want to split on. I'm planning on have ; and , as the defaults, and it sounds like I should probably add space as well.

**Comment by TOMKHAN** [comment]
I thought you were mad at me, man! Thanks once again for the great work :+1:
