### ISSUE TITLE
Updating adapter

### ISSUE THREAD

**Issue by CapitanRedBeard** [splitwise/TokenAutoComplete#110]
Could you implement a way to update the list so I can call an async task loading in the adapter?
A member in the earlier issue states how it would be possible

**Comment by mgod** [comment]
I'm assuming you're referring to #74, which I'd love to accept a pull request for, though I haven't had time to see if the suggested implementation works well myself.

**Comment by CapitanRedBeard** [comment]
Yes that is the one! How does one give you the option to accept a pull request? Sorry for my simple question, I'm new to git

**Comment by mgod** [comment]
@CapitanRedBeard someone would have to fork this repository and make the changes, then submit a pull request to me. Once I've looked it over and made sure the code works well with everything else, I can merge the request. This is probably the most useful overview of the process: https://help.github.com/articles/creating-a-pull-request/
