### ISSUE TITLE
Should hide keyboard when popup list is scrolled

### ISSUE THREAD

**Issue by hellobenny** [splitwise/TokenAutoComplete#112]
I noticed that the vanilla AutoCompleteTextView, in certain situation, has the behavior of hiding the keyboard when the user starts scrolling on the autocompletion list. The certain situation is when the popup is very close to the edge of the keyboard. It does this so there is more room to see the options in the list. 

Even though I see TokenCompleteTextView inherits from AutocompleteTextView (through MultiAutoCompleteTextView), this behavior seeems to be disabled, as the keyboard will never hide in any situation.

**Comment by mgod** [comment]
I think this might be a layout change rather than something core in the TextView. Can you try some of the suggestions on http://stackoverflow.com/questions/14750786/scrolling-drop-down-menu-over-the-keyboard-in-autocompletetextview and see if any of those work?
