### ISSUE TITLE
currentCompletionText() is buggy while tokens are collapsed

### ISSUE THREAD

**Issue by Saketme** [splitwise/TokenAutoComplete#113]
Hello, I have a use case where I call `performCompletion()` manually, which in turn calls `currentCompletionText()` internally. A small bug here in `currentCompletionText()` is that it doesn't ignore any CountSpans ("+1") present in the text. This ofcourse happens while tokens are collapsed.

I'm ignoring this bug at my side in two steps. First, by:

    // Bug workaround: "+1" is getting caught while tokens are collapsed
    final CountSpan[] countSpans = editable.getSpans(0, editable.length(), CountSpan.class);
    for (CountSpan countSpan : countSpans) editable.removeSpan(countSpan);

Strangely, this doesn't work always at my side. So the second step uses a "[Jugaad](http://www.urbandictionary.com/define.php?term=jugad&defid=2392153)" method:

    final String completionText = TextUtils.substring(editable, start, end);
    return CountSpan.isCountSpanText(completionText) ? null : completionText;

`isCountSpanText()` is a simple method that checks if the text is a "+" followed by a digit.

This goes without saying, but fixing this issue will also involve ignoring null returns from `currentCompletionText()` inside `performCompletion()`.
 
I hope I was able to explain this bug clearly. Sorry for not sending a pull request as I believe mine's not a perfect implementation yet.

**Comment by mgod** [comment]
So the removeSpan function just remove the span attribute on the text, it doesn't remove the underlying text, which is probably the reasons it's not working the way you intend. You probably want to run something more like:

```
text.delete(text.getSpanStart(countSpan), text.getSpanEnd(countSpan));
text.removeSpan(countSpan);
```

**Comment by Saketme** [comment]
Aha, that seems to do the trick. Thank you :)

**Comment by mgod** [comment]
I wasn't sure where in the library you were making that change. Which method were you modifying? PR would be awesome as well.

**Comment by Saketme** [comment]
Okay, I will do that :)

**Comment by mgod** [comment]
After fussing with this for a while, it seems like you shouldn't call perform collapse if the view is already collapsed? I spend a little time fussing with this fix and I haven't been happy with any of my solutions.

**Comment by Saketme** [comment]
Not "collapse", but "completion". Calling `performCompletion()` while the view is collapsed is buggy.

**Comment by mgod** [comment]
I'm having trouble setting up a scenario where I have text to be completed while the view is collapsed. Can you tell me what your settings are on the completion view?

**Comment by Saketme** [comment]
Apologies for the delay. I don't have access to my laptop right now. AFAIK I'm manually calling performCompletion() when I need to extract the recipients, regardless of whether the View is collapsed or not. I am doing to ensure completing any unfinishing tokens when the user performs a send action. 

Now, I don't exactly remember why I added this. I guess the older versions of TokenAutoComplete used to miss completing tokens in some rare cases and this extra step solved that problem. 

Does this help in any way?

**Comment by mgod** [comment]
I think I've caught mot of the completion cases where this would be an issue, so I'm closing this out as I haven't been able to repro.

**Comment by Saketme** [comment]
Cool, thanks :)
