### ISSUE TITLE
Unable to enter comma character from softkeyboard

### ISSUE THREAD

**Issue by hzsweers** [splitwise/TokenAutoComplete#114]
I might be missing something, but is there anything in the library that would disable entering commas? Works fine with a regular edittext. Running on v1.3.1 (modified jar with min SDK version set to 14).  Doesn't matter what conditions the comma is entered in (middle of word, beginning of input, end of word, after whitespace, etc).

**Comment by mgod** [comment]
well, a comma will complete the current token, so if you're hitting a comma with nothing in the field (or not allowing random completions) it will just ignore the input. If you want to be able to enter commas, you'll need to use ```setSplitChar``` to change the token split character to something else so commas will not get special handling.
