### ISSUE TITLE
backspace is not deleting anything.

### ISSUE THREAD

**Issue by venkatesh3007** [splitwise/TokenAutoComplete#115]
I am using android 5.0.1 and TokenAutoComplete 1.3.2.

When I try to delete the text with the backspace there is no response. The text remains the same.

**Comment by kukuhyoniatmoko** [comment]
me too, there is nothing happen when delete key is pressed
I'm trying different TokenDeletionStyle and TokenClickStyle, still nothing happened
I'm using 4.4.2

**Comment by mgod** [comment]
Terribly sorry about that! Did a merge that seemed trivial and didn't double check soft keyboard delete after. This should be fixed in 1.3.3.

**Comment by venkatesh3007** [comment]
@mgod gradle is not able find 1.3.3 in android-studio.

**Comment by mgod** [comment]
@venkatesh3007 Looks like the release hasn't been synced to Maven Central yet. I'd expect it up in the next hour or two.
