### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Laimiux** [splitwise/TokenAutoComplete#117]
Should System.out.println be used in Android? Also, shouldn't we be able to turn logging on and off?

**Comment by mgod** [comment]
Well, I should probably remove the debug statement in ```deleteSurroundingText```, but the other print statements in the code you should only see if you (the developer) are doing something wrong. I suppose I should probably move the other statements to Log.e

**Comment by mgod** [comment]
I've updated the logging in 0051f0e6ad114464a69d6c726dce17db40c34ac7. I'll include this in the next release.
