### ISSUE TITLE
Show keyboard when token is selected

### ISSUE THREAD

**Issue by niteshkhatri** [splitwise/TokenAutoComplete#118]
Hi, thanks for such a great library. I am having a little problem. When I click on TokenCompleteTextView to write something keyboard comes up. However if keyboard is not visible and I click on a token or select a token, keyboard is not showing. I want to show keyboard when token is clicked so that user will be able to press backspace to remove it.

**Comment by mgod** [comment]
Hmmmm, when I'm testing, the specific odd behavior that I'm seeing is that if I have the field focused, then dismiss the keyboard, then select a token, the keyboard does not reappear, which honestly feels like how it should probably work. I'm not seeing a case where the keyboard does not appear when I click on a token in the field other than this on. Can you try with the sample project and give me very specific tests of the bad behavior if you see it there?

**Comment by niteshkhatri** [comment]
Here are my test case steps. the field is focused, then dismiss the keyboard, then add some tokens programatically, then select a token, the keyboard does not reappear. What I want is when I select the token the keyboard should reappear so that I can press the backspace key to delete the token. The token click style I am using is TokenCompleteTextView.TokenClickStyle.SelectDeselect. To delete any selected token I need to backspace and to press backspace I want the keyboard to reappear.

**Comment by mgod** [comment]
I think to get the behavior you want, you'll need to override ```onTouchEvent``` and have it force the keyboard to appear manually. The underlying edit text is probably not making the keyboard appear because the selection is not changing, and so it thinks the user wants the keyboard to stay disappeared.

**Comment by niteshkhatri** [comment]
Where can I override onTouchEvent? Should I override it in Activity?

This is what I tried in Activity

        @Override
    public boolean onTouchEvent(MotionEvent event) {
       InputMethodManager imm = (InputMethodManager) activity.getSystemService(Context.INPUT_METHOD_SERVICE);
        imm.toggleSoftInput(InputMethodManager.SHOW_FORCED,0);
        return super.onTouchEvent(event);
    }

I am still not able to show the keyboard.

**Comment by mgod** [comment]
You should override it in your subclass of TokenCompleteTextView.
