### ISSUE TITLE
Handle KEYCODE_SPACE on onKeyDown

### ISSUE THREAD

**Issue by plpt88** [splitwise/TokenAutoComplete#119]
Case for KeyEvent.KEYCODE_SPACE isn't working.

 @Override 
   public boolean onKeyDown(int keyCode, @NonNull KeyEvent event) { 
         boolean handled = false; 
         switch (keyCode) { 
            case KeyEvent.KEYCODE_TAB: 
            case KeyEVent.KEYCODE_SPACE:
                Log.d("SPACE", "SPACE");
                    break;
             case KeyEvent.KEYCODE_ENTER: 
             case KeyEvent.KEYCODE_DPAD_CENTER: 
                 if (event.hasNoModifiers()) { 
                     shouldFocusNext = true; 
                     handled = true; 
                } 
                 break; 
            case KeyEvent.KEYCODE_DEL: 
               handled = deleteSelectedObject(false); 
              break; 
        } 

 
        return handled || super.onKeyDown(keyCode, event);      
}

**Comment by mgod** [comment]
What are you trying to make happen here? Maybe just use the setSplitChar method?

**Comment by mgod** [comment]
Unless I've misunderstood, you should use something like ```setSplitChar(' ')```
