### ISSUE TITLE
Allow Selection Mode that only selects, but does not delete

### ISSUE THREAD

**Issue by jchaager** [splitwise/TokenAutoComplete#121]
It would be useful if there were a TokenClickStyle that allows the user to tap on an item to select  it, but did not delete it on a second click.  The user would then use either the backspace key on the keyboard, or the swipe up motion to delete the token.

**Comment by mgod** [comment]
I think the TokenClickStyle.SelectDeselect will do what you want. I should probably add that to the README...

**Comment by jchaager** [comment]
That isn't really the behavior I'm looking for though. I'd like tapping to select the token, and tapping in the empty space at the end of the line to unselect. The SelectDeselect toggles back and forth.

**Comment by mgod** [comment]
So I think the only piece of behavior you'd want changed from how SelectDeselect works is to not allow the second click to unselect the object?

**Comment by jchaager** [comment]
Correct. That's what I originally thought the Selct mode did, but that turns out to be more accurately describe as a SelectDelete mode.

**Comment by mgod** [comment]
hmmmm. I guess I feel like the SelectDeselect mode comes close enough to your behavior that I'm not sure it makes sense to add anything to the core project to do something different. Is there a reason that allowing a second click on a selected token to unselect the token is a problem?

**Comment by jchaager** [comment]
I'm trying to mimic behavior in our iOS and desktop apps where clicking a token selects it, but clicking again doesn't deselect it. We want to maintain as much consistency across the platforms as possible.

**Comment by mgod** [comment]
While I don't think this quite makes sense to include in the core project, you should be able to override this behavior by overriding ```buildSpanForObject``` in your ```TokenCompleteTextView```. Create your own subclass of ```TokenImageSpan``` to return from ```buildSpanForObject``` and override ```onClick```. In your ```onClick``` implementation, simply return if ```view.isSelected()``` returns true, otherwise do the parent behavior.

**Comment by jchaager** [comment]
That solution seems to work great.  Thanks for the suggestion.

**Comment by mgod** [comment]
Awesome! I'm glad we could get this working well for you.
