### ISSUE TITLE
when i typed into edittext and select item from the adapter, typed text was not remove.

### ISSUE THREAD

**Issue by MikhilPastagia** [splitwise/TokenAutoComplete#124]
like, 
i typed "n", now i select any item then n+selected item both are display in edittext. so how to remove "n" from edittext after selecting the item. and also i have to edittext remove text callback to unselect items of listview.

**Comment by mgod** [comment]
I'm not able to reproduce this. It sounds like you're adding some custom callbacks to the EditText? You're probably removing some callback the library needs to clear text. Can you provide a code sample?

**Comment by MikhilPastagia** [comment]
its clear. i solve that... thanks for reply...
