### ISSUE TITLE
setTokenLimit(), app crashes when more than the limit will be added

### ISSUE THREAD

**Issue by Kkoile** [splitwise/TokenAutoComplete#126]
Without setting any token limit, the library works fine. But when I set the token limit to 1 or 2, the app crashes every time I try to add one token more than the limit.
In my understanding this should not happen. If I need to check if the token limit has been reached, the method doesn't make any sense...

**Comment by mgod** [comment]
Can you provide a stack trace of the crash?

**Comment by mgod** [comment]
This is fixed in 3b0f86f59e10d62751c53a91957f4786c38f2269. Expect 2.0 to include this fix.
