### ISSUE TITLE
some extra characters in getText()

### ISSUE THREAD

**Issue by osemen-remit** [splitwise/TokenAutoComplete#128]
Hi,
I'm using your lib for tagging users in comments, so there should be some text beside tokens. But when I use `getText().toString()` it contains some commas where tokens were added.
Is it possible to get raw text ?
Thanks.

**Comment by mgod** [comment]
Unfortunately, it's not possible to get a clean string out of ```getText()```. The implementation of the system is really not set up to handle mixed input like that. If you want to build the string from ```getText()```, you should replace each pair of commas with the next item from ```getObjects()``` in order.

**Comment by osemen-remit** [comment]
Thanks @mgod
