### ISSUE TITLE
Can we limit the number of characters for a token?

### ISSUE THREAD

**Issue by jyothish6190** [splitwise/TokenAutoComplete#129]
I want to limit the number of characters allowed in a single token. Is there is any such functionality available?

**Comment by mgod** [comment]
Can you give me some more details on why you want this? I can't really think of a reason you'd need to limit the number of characters.

**Comment by jyothish6190** [comment]
I included this library to my project. It contains a small edit text. When I type a lengthy mail id it gets duplicated.

**Comment by mgod** [comment]
I'm still not sure I quite understand what's going wrong. Can you send me a screenshot?

**Comment by mgod** [comment]
I haven't heard back on this, so I'm going to go ahead and close it.
