### ISSUE TITLE
AppCompat v22 support

### ISSUE THREAD

**Issue by malbarando** [splitwise/TokenAutoComplete#132]
Hi,

I'm using AppCompat v22 and it now supports AppCompatMultiAutoCompleteTextView for widget tinting.
Is there a way to use this instead of extending MultiAutoCompleteTextView? Thanks!

**Comment by mgod** [comment]
It may just work if you modify the library to have the token view extend the support library class. I'm not sure I'm ready to force use of the support library or have two different versions of the token view out there yet.

**Comment by sosite** [comment]
+1

**Comment by bugraoral** [comment]
For future reference, simply extending from AppCompatMultiAutoCompleteTextView works, but I agree with not having a dependency to support lib is important

**Comment by mgod** [comment]
Good to know. I'm actually planning to deprecate the current version and build 3.0 around material design principles and use the AppCompat versions. It's a little more complicated change than just swapping out the parent, so it seemed like I should hold off on adding the dependency until I'm developing around it.

**Comment by mgod** [comment]
Version `3.0.0` now inherits from AppCompat.
