### ISSUE TITLE
Is there a way to always visualize the dropdown list?

### ISSUE THREAD

**Issue by Alien1993** [splitwise/TokenAutoComplete#137]
I need to always visualize the dropdown list of options to autocomplete even after I click something on the list. As of now when I click an item in the dropdown it is dismissed and not visualized until I type something else, this behaviour is not what I need. Is there a way to do this?

**Comment by jnsone11** [comment]
In your class extending AutocompleteTextview try override "enoughToFilter" to just "return true";

**Comment by Alien1993** [comment]
I already do that but it doesn't work properly.

   @Override
    public boolean enoughToFilter() {
        return true;
    }

    @Override
    public void onFocusChanged(boolean focused, int direction, Rect previouslyFocusedRect) {
        super.onFocusChanged(focused, direction, previouslyFocusedRect);
        if (focused) {
            performFiltering(getText(), 0);
        }
    }


This way when the View receives focus the first time the dropdown is visualized but if I touch again the view or a token is added the dropdown is dismissed. I need it to remain even in case of those two events.

**Comment by jnsone11** [comment]
In your onItemClick try adding:

FOKUS.request(yourAutocompleteTextview);

public class FOKUS {

    private static Context context = yourGetContextFunc();

    public static void request(View view){
        dispatch(view);
    }

    public static void request(final View view,long millisDelay){
        Handler handler = new Handler(context.getMainLooper());
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                dispatch(view);
            }
        }, millisDelay);

    }

    private static void dispatch(View view){
        view.dispatchTouchEvent(MotionEvent.obtain(SystemClock.uptimeMillis(), SystemClock.uptimeMillis(), MotionEvent.ACTION_DOWN, 0, 0, 0));
        view.dispatchTouchEvent(MotionEvent.obtain(SystemClock.uptimeMillis(), SystemClock.uptimeMillis(), MotionEvent.ACTION_UP, 0, 0, 0));
    }
}

**Comment by Alien1993** [comment]
Nothing changes, the behavior is the same.

**Comment by jnsone11** [comment]
How about fetching the item touch event, process whatever you want to process but return false to the touchListener. If I get you right, you don't want the dropdown to close. If you don't process the touch event technically there wasn't any "choice". Give it a shot..

**Comment by Alien1993** [comment]
I think I'm going to ditch this approach for something simpler, this might take me too much time. Thank you anyway.

**Comment by mgod** [comment]
I see you've already looked over suggestions for the base class, so I think looking for something simpler probably makes sense.
