### ISSUE TITLE
OnClick Handlers for each token

### ISSUE THREAD

**Issue by zameermfm** [splitwise/TokenAutoComplete#139]
Is it possible to have overrides OnTokenSelected functions like now you guys have
public void onTokenAdded(Object token) {
  
    }

?

**Comment by mgod** [comment]
What do you need these for? There are some different solutions to respond to token selections depending on what you are doing.

**Comment by zameermfm** [comment]
Tokens are just names of reciepient for us, each recipient will have information which will popup on clicking each token. We need to show an Intent for each token. So, how is possible to respond to selection of each token?

**Comment by zameermfm** [comment]
If possible, Can you specify the solutions?

**Comment by mgod** [comment]
So I think the most reasonable solution in your case is to create a custom view for your token and override the ```setSelected``` method to display/hide your popup. You should be able to follow the custom view docs here with some modification: https://github.com/splitwise/TokenAutoComplete#example-custom-view

It might also be worth reading over https://github.com/splitwise/TokenAutoComplete/issues/121 if that isn't flexible enough for you.

**Comment by zameermfm** [comment]
What I have now is a custom view and it really fires setSelected but this
public class TokenLayout extends LinearLayout {
    ...
    @Override
    public void setSelected(boolean selected) {

 //WE CANNOT START AN ACTIVITY HERE

**Comment by mgod** [comment]
You're right, I hadn't thought that through all the way. So the other way to deal with it is to create your own custom ```TokeImageSpan``` in your subclass of ```TokenCompleteTextView```:

```
protected class ClickableTokenImageSpan extends TokenImageSpan {
        public TokenImageSpan(View d, T token, int maxWidth) {
            super(d, maxWidth, token);
        }
        
        @Override
        public void onClick() {
                //You should have access to the activity here
        }
}
```

the override ```buildSpanForObject``` to use your custom class:

```
protected TokenImageSpan buildSpanForObject(T obj) {
        if (obj == null) {
            return null;
        }
        View tokenView = getViewForObject(obj);
        return new ClickableTokenImageSpan(tokenView, obj, (int)maxTextWidth());
    }
```

**Comment by zameermfm** [comment]
In
<code>return new ClickableTokenImageSpan(tokenView, obj, (int)maxTextWidth()); </code>
maxTextWidth has private access and it cannot be compiled. 
Declaration of this property is given as  
<code>private float maxTextWidth() { /* compiled code */ }</code>

So how to work around it?

**Comment by zameermfm** [comment]
And startActivity is not available in this either. If it's ok, could you be more specific on how to start an activity? 
<code>
@Override
        public void onClick() {
            
        }
</code>

**Comment by mgod** [comment]
For starting an activity in there, call ```getContext().startActivity(/* your intent */);```. I should probably make maxTextWidth protected, but you can use the implementation for it for now, which is ```getWidth() - getPaddingLeft() - getPaddingRight()```.

**Comment by zameermfm** [comment]
Works super fine, thank you a million. May be you should make this as a feature. Thanks.

**Comment by ashdavies** [comment]
This is really helpful thanks guys
