### ISSUE TITLE
On select token color is not changing

### ISSUE THREAD

**Issue by himanshu1706** [splitwise/TokenAutoComplete#140]
I am creating a project using this library. I have changed the default and selected token color in xml , when I run the program default token color is changed to blue but when I select any token it shows only default color. On select it must change the color which not happening. Please guide me on this issue.

**Comment by mgod** [comment]
Please provide the xml for your token and background. 



—

**Comment by himanshu1706** [comment]
I have resolved the issue by changing the line 89 in TokenCompleteTextView to 
private TokenClickStyle tokenClickStyle = TokenClickStyle.Select;
instead of 
private TokenClickStyle tokenClickStyle = TokenClickStyle.None;
