### ISSUE TITLE
TokenClickStyle.Delete

### ISSUE THREAD

**Issue by robisaks** [splitwise/TokenAutoComplete#142]
The clicks appear to only be captured if the text field is currently selected. If you have multiple TokenAutoComplete fields on the same page, tapping a token in a non-focused field will just select that field, place the cursor next to the token you selected, then bring up the keyboard.

**Comment by mgod** [comment]
I think I have to mark this as won't fix. It adds a lot of odd/bad UI behaviors to have the field respond like this when it's not focused. If you want this behavior, you'll need to fork the project and remove the ```isFocused()``` check on line 519 of the ```TokenCompleteTextView```
