### ISSUE TITLE
Cannot select token.

### ISSUE THREAD

**Issue by doyunglee** [splitwise/TokenAutoComplete#144]
I am running the example on an Android phone running Lollipop and I am unable to select the tag tokens.

**Comment by mgod** [comment]
Did you set the token click style on the completion view?

**Comment by doyunglee** [comment]
I just created a pull request about it, actually! Is that the way to go about it?

**Comment by mgod** [comment]
You did set up the pull request correctly, but you should be configuring the selection style outside of the class file. If you look at the ```TokenActivity``` class, you can see where I configure the ```completionView``` around line 60. This is where you should be changing the selection style.
