### ISSUE TITLE
Double deleting

### ISSUE THREAD

**Issue by doyunglee** [splitwise/TokenAutoComplete#145]
If I put the cursor in between two tokens and press backspace on the keyboard, both tokens are deleted.

**Comment by SunnyMopada** [comment]
We too got the same error.. Author bro.. please reply ASAP

**Comment by mgod** [comment]
I won't be pushing out a release with this for a day or two, but it should be available soon, or you can build your own jars if you need it immediately.

**Comment by edward-s** [comment]
bug still exists even after in the latest commit

steps to reproduce the bug:
1) add 2 or more tokens
2) *rotate the device* forcing a configuration change
3) position the cursor between the 2 tokens and hit backspace
4) bug = both tokens get deleted

without step 2 -rotation, it's ok

**Comment by mgod** [comment]
@doyunglee @SunnyMopada @edward-s I just pushed a new fix attempt that I think is more solid. Can you let me know if this fixes the issue for you?

**Comment by sikoried** [comment]
Hey, thanks for the fix!  Would you mind adding a tag/release following this commit, so it's easier to get through gradle?

Thanks!

**Comment by mgod** [comment]
2.0.1 should be available in Maven Central in a couple of hours.

**Comment by sikoried** [comment]
Thanks!
