### ISSUE TITLE
 error: unclosed character literal

### ISSUE THREAD

**Issue by rambabupudari** [splitwise/TokenAutoComplete#149]
Hi,
I have used your lib in my project. At the time of compile i  got  compile time error in android studio like below for the '§' character
 
Error:(297, 72) error: unclosed character literal
Error:(297, 74) error: illegal character: '\u00a7'
Error:(297, 75) error: unclosed character literal
Error:(297, 88) error: ']' expected
Error:(297, 89) error: illegal start of expression
Error:(297, 90) error: ';' expected
 
I have enable UTF-8 file encoding in  settings.
please help me.
thanq you in advance

**Comment by mgod** [comment]
Everything appears to be saved in UTF-8 on my end. Is it possible your IDE is incorrectly detecting the encoding on the file? You can see some advice for figuring this out here: http://blog.jetbrains.com/idea/2013/03/use-the-utf-8-luke-file-encodings-in-intellij-idea/
