### ISSUE TITLE
How to stop the afterTextChanged() method when token is added and runs again when any character from softkeyboard is pressed

### ISSUE THREAD

**Issue by himanshu1706** [splitwise/TokenAutoComplete#152]
Hello, Thanks for awesome library. I am working on an app and I want a feture like that when a token added or removed from textfield text change listener methods will not work but when a character is added change listener methods will work. Can you please guide me achieve this.

Thanks

**Comment by mgod** [comment]
This is probably nearly impossible. Can you tell me why you want to disable this?
