### ISSUE TITLE
Token callbacks happen when dynamically adding/removing data

### ISSUE THREAD

**Issue by massivespace** [splitwise/TokenAutoComplete#153]
In my fragment's onViewStateRestored() method, I clear and initialize the autocomplete view with some tokens, by calling clear(), and then call addObject() for each token.  This causes my onTokenRemoved() and onTokenAdded() methods to get called.  These methods update my database and send commands to store the new data remotely.  This is a problem, because I don't want to use bandwidth to do this when I'm just initializing the field.

I looked for an exposed API to add and remove tokens via code without having those callbacks issued, but I couldn't find any.  A new API to do this would be nice, because I'm sure other people have written their code to rely on the fact that these methods get called when they add/remove dynamically in code, and I wouldn't want to break them.  But technically, according to the documentation, these callbacks should only be issued when the user adds or removes tokens, not the software.

**Comment by mgod** [comment]
I think I'm going to decline this unless we hear from a lot of other people wanting this feature. In your case, it sounds like you could just disable your callbacks while you're adding the tokens programatically.

**Comment by massivespace** [comment]
Disabling the callbacks does not work for me. I disable the callbacks, then call addObject repeatedly,  then set the callbacks, in the same frame. Then up to 150 ms later,  the callbacks are issued for those addObject calls. I put a nasty work around by only setting the callbacks 200 ms after calling addObject, which works for most devices. I believe the callbacks are called based on when the Span appears, not when the object is added to the list.
On Aug 20, 2015 10:59 AM, Marshall Weir <notifications@github.com> wrote:I think I'm going to decline this unless we hear from a lot of other people wanting this feature. In your case, it sounds like you could just disable your callbacks while you're adding the tokens programatically.

**Comment by mgod** [comment]
Ah, yes, that's true. There are some bad design choices that are now hard to change that make it work that way. I would have the service handling the callbacks get told to ignore whatever objects you add programatically. It sounds like you're just trying to restore the view state, though. Have you looked at https://github.com/splitwise/TokenAutoComplete#restoring-the-view-state ?
