### ISSUE TITLE
example app, the text input after resuming activity is backwards

### ISSUE THREAD

**Issue by weltan** [splitwise/TokenAutoComplete#154]
Hi,

I came across a strange bug in the example app relating the placeholder text and backgrounding. I didn't see it mentioned elsewhere.

Steps to reproduce:
1) Open the app, in the To: field, remove the initial two token emails. Placeholder text "enter a name or email address" should now appear.
2) Background the app.
3) Re-open the app, attempt to type in the To: field. Placeholder text does not disappear, and text is entered in reverse.

Image:
![img_1332](https://cloud.githubusercontent.com/assets/5177887/8884152/651b4270-3209-11e5-82f7-fb32e3d522f5.JPG)

Also, not sure if this could cause problems, I built the example app with the following:
ANDROID_BUILD_MIN_SDK_VERSION=15
ANDROID_BUILD_TARGET_SDK_VERSION=22
ANDROID_BUILD_SDK_VERSION=22
ANDROID_BUILD_TOOLS_VERSION=22.0.1

and used 
classpath 'com.android.tools.build:gradle:1.2.3'

**Comment by weltan** [comment]
update: i rebuilt using the default build tools and SDK versions, still was able to reproduce the bug.

Also, this is using the most recent branch of master, 2.0.1/7. Haven't tested older versions for regression.

**Comment by mgod** [comment]
I've started seeing this myself a couple of times now, so maybe I'll be able to track it down.

**Comment by sajadbanooie** [comment]
same issue the text typed reversed

**Comment by sajadbanooie** [comment]
i have removed the set prefix line
everything is working fine now
