### ISSUE TITLE
Tokens deleted without selecting it by pressing the softkeyboard delete key.

### ISSUE THREAD

**Issue by himanshu1706** [splitwise/TokenAutoComplete#155]
I am facing a issue in the library that if I single or multiple tokens on field and without selecting any of them when I press soft keyboard delete key tokens get deleted. I want that if no token is selected and when use press the delete key none of the token should be deleted but when we type some characters to search the names and press delete key characters must delete.

Please guide me to achieve this.

Thanks.

**Comment by himanshu1706** [comment]
is there anyone who faced this issue?

**Comment by mgod** [comment]
Sorry for the slow response. This is expected behavior. You might take a look at #161 which I'll merge the next time I go over this library.
