### ISSUE TITLE
Backspacing a character after a token doesn't delete the character and de-tokenises the token

### ISSUE THREAD

**Issue by walid-halabi-myob** [splitwise/TokenAutoComplete#156]
Hi,

I've tried this in the SplitwiseTokenExample so it's a legitimate bug.

Steps to reproduce:
* Open the example app
* Type abc@def.com and press comma (the email becomes a token)
* Type z and press backspace
* **the email is no longer a token**
* **the z is still there, with no space between it and the email address**

I assume the correct behaviour is that the Z is deleted, and the email remains as a token.

**NOTE: this doesn't happen in the Splitwise app**

The contents of the field after the above process are as below:
<img width="291" alt="screen shot 2015-07-27 at 3 57 18 pm" src="https://cloud.githubusercontent.com/assets/11152432/8899468/34f48f72-3478-11e5-93fb-be3238e053ff.png">

**Comment by walid-halabi-myob** [comment]
Still happens in 2.0.1

**Comment by mgod** [comment]
I think I've fixed this in master, but I can't seem to reproduce the problem at all any more. Can you see if you can cause the issue in the current HEAD version?

**Comment by walid-halabi-myob** [comment]
Thanks, we've moved away from using this library, but I'll see if I can get a quick test in

**Comment by mgod** [comment]
Have you moved to a different library for this or just away from token fields?

**Comment by walid-halabi-myob** [comment]
Tried a couple others, they either have no tests or have bugs or both, so we dropped down to text

**Comment by walid-halabi-myob** [comment]
Also, when experimenting with Spannable and friends, we noticed unusual behaviour with non-standard keyboards like the HTC keyboard or the Samsung keyboard - I can't remember the details but I'd suggest having a test

**Comment by mgod** [comment]
Yeah, unfortunately, I haven't seen a good way to build automated tests that would provide any kind of assurance that this works on custom keyboard stuff. A lot of why this project is slow to make changes is that I'm fairly confident the current build works on the Samsung Galaxy blah and HTC One, which appear to be the weirdest standard keyboards. Testing is done manually in a variety of environments, but it's not something I can easily automate.
