### ISSUE TITLE
How to remove the blank spaces between tokens?

### ISSUE THREAD

**Issue by himanshu1706** [splitwise/TokenAutoComplete#158]
Hello, I working for an app and I need to remove the blank spaces between tokens. Can anyone guide me to achieve this?

**Comment by mgod** [comment]
I'm afraid that's not really possible with this library. Why do you need to remove the spaces?

**Comment by himanshu1706** [comment]
Hi I have another issue with this library. I need to include space while typing with keyboard but right now when I hit the space key it adds the string as a token. How can I achieve this?

**Comment by mgod** [comment]
Change the split character.
