### ISSUE TITLE
Is it possible to use it with a CursorAdapter ?

### ISSUE THREAD

**Issue by TheBlusky** [splitwise/TokenAutoComplete#159]
I tried to use the library with an ArrayAdapter, and it's working fine.
But is a CursorAdapter, I got the following exception when I click on a suggestion:
`java.lang.ClassCastException: android.database.sqlite.SQLiteCursor cannot be cast to io.palmtree.appimmo.reference.Location`

(where io.palmtree.appimmo.reference.Location is the object used)

I thing it's because it's written to be used with ArrayAdapter, and from this, you can easily cast an element (which is not possible with a cursor).

But does any one tried with success to do it with a cursor ?
Thx !

**Comment by mgod** [comment]
Extend ```TokenCompleteTextView<Object>``` instead of your ```Location``` class. Then do manual casting of the results to ```SQLiteCursor``` and pull the values out.

**Comment by TheBlusky** [comment]
Excellent ! That did the job :-)
Thx !

**Comment by chrimaeon** [comment]
A better solution would be to override `getItem(int position)` from `CursorAdapter` and return a concrete object you can then use in the `TokenCompleteTextView`

```java
class MyAdapter extends CursorAdapter{

    @Override
    public Person getItem(int position) {
        Cursor cursor = (Cursor) super.getItem(position);
        if (cursor != null) {
            return new Person(cursor.getString(0), cursor.getString(1));
        }

        return null;
    }
}

public class ContactsCompletionView extends TokenCompleteTextView<Person> {
    public ContactsCompletionView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    protected View getViewForObject(Person person) {

        LayoutInflater l = (LayoutInflater) getContext().getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
        TextView view = (TextView) l.inflate(R.layout.contact_token, (ViewGroup) getParent(), false);
        view.setText(person.getEmail());

        return view;
    }

    @Override
    protected Person defaultObject(String completionText) {
        //Stupid simple example of guessing if we have an email or not
        int index = completionText.indexOf('@');
        if (index == -1) {
            return new Person(completionText, completionText.replace(" ", "") + "@example.com");
        } else {
            return new Person(completionText.substring(0, index), completionText);
        }
    }
}
```
