### ISSUE TITLE
Loss Focus

### ISSUE THREAD

**Issue by philwebservicesChris** [splitwise/TokenAutoComplete#162]
Autocomplete displays " +1 "  even if I only have one item/token selected when losses focus.

**Comment by mgod** [comment]
does the token fit completely in the view?

**Comment by philwebservicesChris** [comment]
Yes, and I also have created my custom view of the token.

**Comment by mgod** [comment]
Are you able to reproduce this issue with the example project? I haven't seen this or hear dog it before.

**Comment by philwebservicesChris** [comment]
Yes, kindly see this.

![screenshot_2015-08-24-09-35-39](https://cloud.githubusercontent.com/assets/13564260/9431443/1606184c-4a44-11e5-90a0-a270def3afc1.png)
![screenshot_2015-08-24-09-41-24](https://cloud.githubusercontent.com/assets/13564260/9431459/75023a92-4a44-11e5-9916-bd8f00739996.png)

**Comment by mgod** [comment]
Ah, so the field will collapse whatever it needs to in order to be 1 line, so in your case it's collapsing because the token is wide enough to go to a second line with just one visible.
