### ISSUE TITLE
Remove typed text programatically

### ISSUE THREAD

**Issue by skywall** [splitwise/TokenAutoComplete#163]
Hi, is there any way to remove typed text when object is added programatically through addObject()? I simply want to replace (or delete) all text when new object is added. I've tried updating editable, but this haven't lead to success. Thanks.

**Comment by mgod** [comment]
Not easily. Your best bet is to set your filter length to 1 and call ```performCompletion``` before you ```addObject```. Why do you need to clear the current completion text?

**Comment by skywall** [comment]
Thanks for reply. I'm using ListView instead of dropdown menu. I have added text watcher, where I cut last part of input, for example from string ",, ,, jon" only text "jon" is used in filtering and it works as expected. 

What do you mean with "set your filter length to 1"? Length of what? Thank you.

**Comment by mgod** [comment]
Sorry, I meant ```setThreshold(1)```. This will make it so perform completion will handle the current completion text if there is any. As long as you have ```performBestGuess``` set to true (the default) and your ```defaultObject``` method returns null, this ```performCompletion``` should clear the current completion text.

**Comment by skywall** [comment]
I need let user type email on its own (typing instead of selection from listview) so i can't return null in `defaultObject`.

**Comment by orbitcoder** [comment]
hey Skywall  , facing same issue with library , i am trying to find the solution , if you finds anything please post here .

**Comment by mgod** [comment]
Well, I guess I'd be inclined to return null from ```defaultObject``` after the user has entered an email address. Or have default object check to see if the entered text looks like an email address and return null for non-email address like completions. I'm still a bit puzzled by your use case, so I'm having trouble figuring out good suggestions (they enter an email address and then enter something else random in the field?). I would look at the ```replaceText``` method in the ```TokenCompleteTextView``` to see how I handle text replacement in there. You might also find ```currentCompletionText``` helpful instead of rolling your own completion text detector (though it can be buggy if you call it when the field is collapsed).

**Comment by skywall** [comment]
Many thanks for your help, I have finally solved the problem. Just for completion, my use case:
1) Object can be added dynamically or by typing email followed by split character.
2) I have added `textWatcher` where I cut filtered text from end of string. Simply done by method `currentCompletionText()`. My solution:

1) `TokenCompleteTextView` subclass:

	@Override
	protected Person defaultObject(String completionText) {
		if (completionText.contains("@")) { // simple check, if there is '@'
			for (char splitChar : splitChars) { // ensure, text is ended with split character and object will be created
				if (completionText.charAt(completionText.length()) == splitChar) {
					return new Person(null, completionText, null);
				}
			}
			return null;
		} else {
			return null;
		}
	}

	public void deleteText() {
		Editable text = getText();
		text.replace(text.length() - currentCompletionText().length(), text.length(), "");
	}

2) Add object dynamically wherever needs to be done:

    contactCompletion.deleteText();
    contactCompletion.addObject(person);

Thanks for your great library.

**Comment by orbitcoder** [comment]
Thanks Its Working like a charm !! saved a lot

**Comment by mstedler** [comment]
Hi, i'm having similar issue, what i need is:
when user perform a long press, the method showDropDown() is called and all tokens are shown. 

With and empty TokenCompleteTextView this works fine, but if the user type and select, when the long press is performed the filter is based on previous selection

**Comment by mgod** [comment]
You might try ```notifyDataSetChanged``` or ```notifyDataSetInvalidated``` on the adapter before you call ```showDropDown```

**Comment by deepak786** [comment]
Alternate

Add this to onFocusChanged in TokenCompleteTextView
if(!hasFocus && enoughToFilter()) performCompletion();
