### ISSUE TITLE
How to get charsequence of the newly typed letters removing the previously selected tokens.

### ISSUE THREAD

**Issue by alchemistgo87** [splitwise/TokenAutoComplete#164]
Suppose I have already added 1 token to the view and now typing letters for new token. While typing new letters how can I retrieve just the new letters in onTextChanged() method?

**Comment by mgod** [comment]
You can get the current words being entered by calling ```currentCompletionText```. You may need to make a public accessor in your subclass. What are you using this for?

**Comment by alchemistgo87** [comment]
Thanks a lot. It worked.
I am using this to call a search api which get me the list of suggested tokens.

**Comment by mgod** [comment]
Awesome. You can also provide an adapter to the view that ```extends BaseAdapter implements Filterable``` and the view should automatically handle everything from there.
