### ISSUE TITLE
Text in between tokens for '@' Mentions like twitter

### ISSUE THREAD

**Issue by ashmosaheb** [splitwise/TokenAutoComplete#166]
Hi,

Great library,

I have been trying to use it for '@'Mentions like in twitter. I have almost got it working, except I find I cannot do free text in between tokens eg:

"Hi [TOKEN1] how are you. From [TOKEN2]" 
"Hi [Bob] how are you. From [Steve]"

Is there anyway of achieving this with this library, and do you have any other suggestions for '@'mentions that could be useful?

Thanks.

**Comment by mgod** [comment]
I think you should be able to get this working if you call ```performBestGuess(false)```
