### ISSUE TITLE
unable to add new objects when activity is resumed

### ISSUE THREAD

**Issue by nazmuddin77** [splitwise/TokenAutoComplete#170]
when the activity in which tokenautocomplete is implemented is resumed, although the chips are getting created but getObject() doesnot return newly added chips

**Comment by mgod** [comment]
What Android OS version are you having this problem on?

**Comment by nazmuddin77** [comment]
hey, thanks for replying, its on android 4.2

**Comment by Leminity** [comment]
I have same issue. (5.0.1)

**Comment by Leminity** [comment]
Thir problem occured when I used 2.0.1 version.

I solved issue change to 2.0.2 ver. thx.
(relate issue : #154 )
