### ISSUE TITLE
getObjects() sometimes returns 0

### ISSUE THREAD

**Issue by dkadrikj** [splitwise/TokenAutoComplete#172]
The getObjects() method sometimes returns 0 elements (empty list). I do not have all the details since, the code is production, and we can not replicate. But, it surely exists since a more users had complained about it.

Library version: 2.0.2

**Comment by mgod** [comment]
I should probably make a note of this somewhere in the docs as this is a known flaw in the design. The ```getObjects()``` call will be empty if you call it before the UI has had some cycles to update. ```getObjects()``` returns all objects that have tokens currently visible, so if the token field text has not had a chance to redraw with new tokens, they will not be returned.

I would actually guess (as you can't replicate) that the field is not able to restore the tokens during configuration changes in your app. Try rotating the screen with tokens entered and see if that causes the problem.

**Comment by mgod** [comment]
Version `3.0.0` adds an `addObjectSync` method that should make sure the `getObjects` call is more accurate.
