### ISSUE TITLE
Setting cursor in the middle causes wrong auto complete

### ISSUE THREAD

**Issue by dejarno** [splitwise/TokenAutoComplete#173]
Steps to reproduce:
1. Type email address
2. Set cursor somewhere in the email adress (e.g. after the @)
3. Touch somewhere outside the text field

Result: email is completed up to the cursor
Expected: email is completed up to the next whitespace/comma/...

See attached video
https://vid.me/V7Np

**Comment by dejarno** [comment]
@mgod Is it possible to give feedback? Is there a workaround? Is it considered a bug or will this be dismissed?

**Comment by mgod** [comment]
This is a bug. I don't know any good solutions off hand, but would be happy to have a PR fix for it.

**Comment by mgod** [comment]
I will also look at fixing this myself when I have time, but I think my next round of changes will be to add a test suite to the project (I finally have a good sense of how to test this well automatically).

**Comment by dejarno** [comment]
Hey @mgod, can I have a status update considering this issue? What kind of priority has it, is it something that is planned for the coming weeks or more like there are more important improvements for the coming months?

**Comment by mgod** [comment]
@dejarno this isn't a super high priority. If I have time to spend on the project, I intend to add some tests and work on improving how it works with Material design.

**Comment by dejarno** [comment]
@mgod I've created a PR, if you have any remarks please tell me

**Comment by dejarno** [comment]
@mgod Did you already had some time to take a look at the PR?

**Comment by mgod** [comment]
Sorry to be so slow. Left a comment on the PR, should be quick to change, then I'm happy to merge it.

**Comment by dejarno** [comment]
Hey, you closed this but it isn't released :) any idea when?

**Comment by mgod** [comment]
I'll most likely push out an update later this week.
