### ISSUE TITLE
Update adapter when add/remove token

### ISSUE THREAD

**Issue by nAkhmedov** [splitwise/TokenAutoComplete#174]
How to update adapter when token is added/removed? When i add a token and remove this, still count is 1 mView.getAdapter().getCount() = 1?

**Comment by mgod** [comment]
It depends on how you're building your adapter. The token view doesn't do any special handling of the adapter, it just reads data from it and filters it based on your input. You should probably implement the onTokenAdded/Removed callbacks and remove the object from the adapter when it gets added to the token view.

**Comment by itslayo** [comment]
Hi! I don't know how to fix such bug as:
When I select tokens dropdown list is updating (removing selected tokens) but when I try to remove at least 1 token dropdown appears with whole data (and with tokens that were removed from adapter previously)
```
        completionView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                completionView.showDropDown();
                return false;
            }
        });
 completionView.setTokenListener(new TokenCompleteTextView.TokenListener<String>() {
            @Override
            public void onTokenAdded(final String token) {
                rootView.post(new Runnable() {
                    @Override
                    public void run() {
                        adapter.remove(token);
                        adapter.sort(ALPHABETICAL_ORDER);
                        adapter.notifyDataSetChanged();
                    }
                });
            }

            @Override
            public void onTokenRemoved(final String token) {
                rootView.post(new Runnable() {
                    @Override
                    public void run() {
                        adapter.add(token);
                        adapter.sort(ALPHABETICAL_ORDER);
                        adapter.notifyDataSetChanged();
                    }
                });
            }
        });
```

**Comment by ajitdubey-mob-ibtech** [comment]
When I select data from list easily i can remove from that list. by using below code
mContactsCompletionView.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> arg0, View arg1, int arg2, long arg3) {
				ClearFlyContact clearFlyContact=(ClearFlyContact) arg0.getItemAtPosition(arg2);
                mSearchContactList.remove(clearFlyContact);
                mSearchAddUserAdapter.notifyDataSetChanged();
            }
        });
Easily I am bale to add that object in view. but when I pressed remove button from keyboard how I can add that object again into list.

Thanks,

**Comment by mgod** [comment]
You'll want to listen for users removing tokens: https://github.com/splitwise/TokenAutoComplete#responding-to-user-selections

**Comment by ajitdubey-mob-ibtech** [comment]
I listen in same scenario but when I remove that object from list it is not reflecting in list. using below code

   @Override
    public void onTokenAdded(Object token) {
    Contact contact=(Contact ) token;
    contactLIst.remove(contact);
    mSearchAddUserAdapter.notifyDataSetChanged();  
    }

When I remove tokenObject from my contact list, still that object showing in list when I search again.

Please help. Thanks

**Comment by ajitdubey-mob-ibtech** [comment]
Thanks now working fine. Inside adapter there is one more temp contact list that's why it was showing. now updated temp contact list also  when user add or remove token.

Thanks for your support

**Comment by nAkhmedov** [comment]
@ajitdubey-mob-ibtech  How did u update your adapter when user add or remove token.Please give an example

**Comment by dsdebastiani** [comment]
I' d like an example too, please. I have the same problem. When I update my adapter (adding/removing) after the Activity is resumed, items that were added aren't showed and items that were removed still are showed in the suggestions list.

I'm using an ArrayAdapter with a List of tokens. I add/remove items in list and the adapter is notified. Perhaps is it necessary a custom adapter?

**Comment by dsdebastiani** [comment]
I've found a solution. The problems was with ArrayAdapter, and not with the TokenView.

The method ```notifyDataSetChanged``` don't work in ArrayAdapter after the Activity ```onResume()```: http://stackoverflow.com/a/5092426/3851246. It's necessary call the method on a UIThread or make changes on list using  ```add()```, ```insert()```, ```remove()```, and ```clear()``` on the Adapter, after that you call ```notifyDataSetChanged()``` normally.

Example:
```
@Override
public void onTokenAdded(Object token) {
    Contact contact=(Contact ) token;
    contactLIst.remove(contact);
    mSearchAddUserAdapter.remove(contact);
   mSearchAddUserAdapter.notifyDataSetChanged();  
}

@Override
public void onTokenRemoved(Object token) {
    Contact contact=(Contact ) token;
    contactLIst.add(contact);
    mSearchAddUserAdapter.add(contact);
   mSearchAddUserAdapter.notifyDataSetChanged();  
}
```
