### ISSUE TITLE
TokenClickStyle how does it work ?

### ISSUE THREAD

**Issue by redouane59** [splitwise/TokenAutoComplete#175]
Hello,

I started working with TokenAutoComplete today, and i have some problem with setTokenClickStyle method. Whatever the parameter I choose (None, Delete, or Selecte), the behaviour is always the same : clicking on a token (on the text or on the X), it removes it directly. Did I miss something ? (Other methods as setDeletionStyle are working fine).

Thank you !

**Comment by mgod** [comment]
Often these kinds of issues are device/os/carrier specific. Are you able to reproduce the issue with the example project?
