### ISSUE TITLE
showing all items

### ISSUE THREAD

**Issue by sajadshokri** [splitwise/TokenAutoComplete#178]
if  you call `showDropDown()` it shows the last list created and doesn't show whole items
how to display all items?

**Comment by sajadshokri** [comment]
i did something like this and it's working:

    adapter.getFilter().filter("");
        completionView.postDelayed(new Runnable() {
            @Override
                public void run() {
                    completionView.showDropDown();
                }
            }, 300);

is this the right way?

**Comment by mgod** [comment]
Yep!
