### ISSUE TITLE
Floating label and error

### ISSUE THREAD

**Issue by itslayo** [splitwise/TokenAutoComplete#180]
Is there a way to add floating label and error like with TextInputLayout?
Like described here https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors

**Comment by mgod** [comment]
Sure. At it's core, TokenCompleteTextView is a TextView, so you can keep track of changes the same way you would for a regular field. ```currentCompletionText``` will give you the current incomplete text the user is typing in to figure out if you want to show an error.

**Comment by itslayo** [comment]
I know it. But when I try to wrap TokenCompleteTextView with TextInputLayout it dissapears at all. 
Of course,  I can use setError(), but it isn't showing an error like in material design guidelines.
What am I doing wrong?

**Comment by sosite** [comment]
I guess that your problem is connected with https://github.com/splitwise/TokenAutoComplete/issues/132.
