### ISSUE TITLE
Sometimes function replaceText in TokenCompleteTextView not working properly

### ISSUE THREAD

**Issue by cheryl1511** [splitwise/TokenAutoComplete#181]
As you can see in the attached video, for example I typed: "ma", then I choose "Marshall Weir" from the suggested drop-down list, then I continuted to type some character "kk" , the view will display something like "marshall@example.com makk" . (Ideally it will not cached the last "ma", the expected result will be "marshall@example.com kk" )

Here is the links to video: https://drive.google.com/file/d/0B3P-1-E-14BrM1dQLTVQN2dkaFk/view?usp=sharing

Please fix that bug.

**Comment by mgod** [comment]
I'm unable to reproduce this with the sample project. I've seen this before, though, and I suspect it's a problem with a specific custom keyboard or os version. Can you let me know what Keyboard/OS you're on?
