### ISSUE TITLE
Cannot load image into the custom view using Picasso Library

### ISSUE THREAD

**Issue by ssaxena01** [splitwise/TokenAutoComplete#182]
I’d like to design the token with an image and text. The image has to be loaded via a url. Do you have an example on how to do that? I’m using Picasso library but that call never occurs. It’s called in the getViewForObject(). The placeholder drawable renders fine while the image from the url isn't rendering. Thanks.

Sample  code:
    
        @Override
         protected View getViewForObject(User user) {
              LayoutInflater l =      
                 (LayoutInflater)getContext().getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
                  RelativeLayout view = (RelativeLayout)l.inflate(R.layout.recipient_token, (ViewGroup)
                DelayAutoCompleteTextView.this.getParent(), false);
        TextView nameView = ((TextView)view.findViewById(R.id.token_name));
        nameView.setText(user.getFullName());
        ImageView tokenImageView = (ImageView)view.findViewById(R.id.token_image);
        String url = user.getImageUrl();
      
        Picasso picasso = Picasso.with(context);
        picasso.setLoggingEnabled(true);
                picasso.load(url)
                .fit().centerCrop()
                .placeholder(R.drawable.default_avatar_image)
                .transform(new RoundTransformation(100, 2, false, context))
                .into(tokenImageView);
        return view;
}

**Comment by ssaxena01** [comment]
I found the issue. It had to do with Picasso library's call .fit().centercrop(). Using that isn't letting the image get downloaded.

**Comment by Studentessa** [comment]
Hello @ssaxena01 , it has been a while since you write this question, but I'm having the same issue know. I trying to  load an image from url but i have not success. I've tried both picasso and Universal Load Image libs  (In other parts of the application lib works fine). I think it have to do with background process.  

thanks in advance

**Comment by mgod** [comment]
#247 might be helpful.

**Comment by Studentessa** [comment]
Thanks @mgod , but I had already check that answer, the problem is that I don't really know how to do it. Could you give me and example?

**Comment by mgod** [comment]
I've never used Picasso, but it looks like this might do it:

```
Picasso.with(getContext()).load(url).into(new Target() {
    @Override public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
        // put bitmap into TokenView and invalidate TokenCompleteTextView 
    }
    @Override public void onBitmapFailed(Drawable errorDrawable) { }
    @Override public void onPrepareLoad(Drawable placeHolderDrawable) { }
});
```

**Comment by Studentessa** [comment]
@mgod  thanks again! I will try your procedure, and  that is a big clue to continue! ;)

**Comment by jatin-lakhani** [comment]
@mgod 
Is it working the above solution for the remote image? It's not working for me.
If you have any solution then please share.
