### ISSUE TITLE
tokens and drawable pressed state

### ISSUE THREAD

**Issue by sosite** [splitwise/TokenAutoComplete#185]
a) They're possibility to change a drawable during press on a token? I want to use `TokenCompleteTextView.TokenClickStyle.Delete` and I like to give users a feedback on any onclick events.

Unfortunately set selector with pressed state as background drawable for a token view doesn't work.
```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/chips_bcg_pressed" android:state_pressed="true"/>
    <item android:drawable="@drawable/chips_bcg_normal"/>
</selector>
```
b) Also when I touch down the token, decide "No, not this one!", swipe out and then touch up, token was still deleted. Any options to avoid that?

**Comment by mgod** [comment]
a) No, sorry. The tokens don't have normal selection states.
b) You should use ```TokenClickStyle.Select``` if you want to have confirmation before deleting a token.
