### ISSUE TITLE
Create hastag clouds with TokenAutoComplete

### ISSUE THREAD

**Issue by rusmichal** [splitwise/TokenAutoComplete#188]
Hello,

I using TokenAutoComplete library to create hastags cloud like on image. It works very well but i need one more function.

![screenshot_2015-12-17-11-52-14](https://cloud.githubusercontent.com/assets/15652344/11867985/058c8fca-a4b5-11e5-9ec8-840fa1232148.png)

That mean now if I will type space character then automatic I got a new tags. E.g
I wrote #hello #hello -> |#hello| |#hello| 

But
If I will write
#hello#hello ->  |#hello#hello|

I would like to add one more character split '#' but this char should be displayed after tap on it.
I know about `setSplitChar(char[] split Chars)` but if I will use them then my hashtag doesn't appear in input.

E.g:

1 Scenario: I write #hello# -> |#hello| #
2 Scenario: I write hello# -> |#hello| #

Info:
|#hello| is after renderer new tags with black background.
I hope it is clear for you and it is easy to provide me more information to update your great libaray.
Thanks.

**Comment by mgod** [comment]
You should be able to do this by building your own ```MultiAutoCompleteTextView.Tokenizer``` and setting it after initialization in the ```TokenCompleteTextView```. In the tokenizer, you can set up your own conditions for the start and end of the inputs.
