### ISSUE TITLE
Cursor sits in the middle of token if view changes size

### ISSUE THREAD

**Issue by daviswalker** [splitwise/TokenAutoComplete#189]
Hello, I would like to change the size of a token view when it is selected (to include an x to show that the next tap will delete the token). This widens the view, and the cursor location is not updated, which means it sits underneath the token. Is there any way to force a refresh of the span that corresponds to the token?

**Comment by mgod** [comment]
You can call ```invalidate```, but assuming you have this drawing change for the token view on ```setSelected``` for the token view, it should resize appropriately for you.
