### ISSUE TITLE
TokenClickStyle.SelectDeselect not allow to select multiple token

### ISSUE THREAD

**Issue by jagatappv** [splitwise/TokenAutoComplete#192]

**Comment by mgod** [comment]
This is working as intended. None of the selection styles should allow multiple selections.

**Comment by jagatappv** [comment]
Is there any way to achieve like this? I want that kind of behaviour if its possible.

thanks for replay

**Comment by mgod** [comment]
I'm not sure how hard this would be. I'm not really clear on what behavior you would want from the multiple selections. Can you give me an example of how you would use it?

**Comment by jagatappv** [comment]
I have to add some tokens and don't want to allow to user add or remove token from pre filled list.
I will first populate list and user can only select and deselect from the given tokens.
and whatever token is selected , just want to pass all selected tokens to the WS. 

I don't want to allow user to input new token,just need to display and allowing user to select and deselect from the given token list.

That's it.
Let me add screenshot that will helps you to understand the situation. 

Thanks,
![untitled](https://cloud.githubusercontent.com/assets/10743189/11972294/37fb950c-a918-11e5-8126-c7b8161f0ff6.png)

**Comment by mgod** [comment]
I think this library is a bit overkill for that case, but you can do this with a little tweaking. You'll need to subclass ```TokenImageSpan``` and override the ```onClick``` method to not clear other token selections (this should be a couple lines of code). Then you'll need to override ```buildSpanForObject``` to use your span subclass instead of ```TokenImageSpan``` (this should also be a couple lines of code).
