### ISSUE TITLE
Object remove from token but view shows its id after backspace and this is specifically comes when we shift to other edittext and comes back to token view

### ISSUE THREAD

**Issue by keyuraashra** [splitwise/TokenAutoComplete#202]
I am having wiered issue with library. What I am doing is, adding different users in my token view and when it goes more than 2/3 it will show me 2 tokens and 2+ in view. Now when i shift to other view (EditText) and comes back to token view again and try to delete/remove user the view shows me like "com.riontech.models.User@25541e5b". I think this is id of the user, but at this moment it execute onTokenRemove callback and also removed token from objects but in view i have to backspace manually and remove the data and then it works fine.

Any idea about this specific issue?

**Comment by mgod** [comment]
Hi! You're seeing the toString value of your objects in the view. You should usually see the text that was perviously used to search or no value when you delete the token unless you have set the token delete style to ```TokenDeleteStyle.ToString```. You can try setting different token delete style and see if one works for you, but they're not 100% reliable.
