### ISSUE TITLE
TokenCompleteTextView is showing only in one line with horizontal scoll

### ISSUE THREAD

**Issue by rajesh130jadav** [splitwise/TokenAutoComplete#204]
TokenCompleteTextView is showing only in one line with horizontal scolling.

I have tried with allowCollapse(false); but no luck.

Please help.

**Comment by mgod** [comment]
It's not possible to have multiple lines and horizontal scrolling. I'm not sure what your use case is, but the TokenCompleteTextView must be assigned a set width in order to do multiple lines.
