### ISSUE TITLE
How can i change multiple Token background color automatically?

### ISSUE THREAD

**Issue by nAkhmedov** [splitwise/TokenAutoComplete#210]
I need to change token background color after onTokenAdded. Is it possible to do that?

**Comment by nAkhmedov** [comment]
For example I have a four TokenLayout. I wanna check these emails are our domain emails or external like example@gmail.com. If either of them is external email i want to change it`s background color as red.

**Comment by nAkhmedov** [comment]
Otherwise green color. Checking proccess is taking some time that`s why i couldn`t impelemnt this logic in getViewForObject method.

**Comment by mgod** [comment]
Please see this issue for comments up changing the token view contents: #5 

Basically, you either need to return a custom view from ```getViewForObject``` and update that view or hang on to the layout you inflate, change it, then call ```invalidate``` on the token view.

**Comment by nAkhmedov** [comment]
I have tried to use second way: "hang on to the layout you inflate , change it, then call invalidate on the token view" _invalidate_ method don`t help me.

**Comment by nAkhmedov** [comment]
after setting new drawable 
searchView.getTokenLayout().setBackground(context.getDrawable(R.drawable.token_external_recipient));

it doesn`t refresh, if i starting type somthing  else after thar token view is changing

**Comment by mgod** [comment]
Sorry, I may have been unclear on a point - you should be calling ```invalidate``` on the ```TokenCompleteTextView``` subclass, not the individual token view. Does this help?

**Comment by nAkhmedov** [comment]
It really works like charm. Tahnk you @mgod!! I had made a mistake by calling _invalidate_ of View not ~TokenCompleteTextView ~. :) :+1:

**Comment by nAkhmedov** [comment]
@mgod Sorry for distrubing I have a question for you? After changing background color of token i moved cursor to another view and back(example@bla.com+3). In result tokens background color are changed to default? How can i manage it?

**Comment by mgod** [comment]
The tokens will be recreated using calls to ```getViewForObject```, so you'll need to keep track of which tokens are selected and return the selected version of the view from there.

**Comment by nAkhmedov** [comment]
@mgod Thank you so much for your response. It really helps
