### ISSUE TITLE
setAdpter() does not setting my arraylist to completion view

### ISSUE THREAD

**Issue by jagatappv** [splitwise/TokenAutoComplete#213]
Hey,

I'm using the same code as you have given

        people = new Person[]{
                new Person("Marshall Weir", "marshall@example.com"),
                new Person("Margaret Smith", "margaret@example.com"),
                new Person("Max Jordan", "max@example.com"),
                new Person("Meg Peterson", "meg@example.com"),
                new Person("Amanda Johnson", "amanda@example.com"),
                new Person("Terry Anderson", "terry@example.com")
        };

        adapter = new ArrayAdapter<Person>(this, android.R.layout.simple_list_item_1, people);

        completionView = (ContactsCompletionView)findViewById(R.id.searchView);
        completionView.setAdapter(adapter);

But my completionView doesn't fill the above list.
I can add text by inputting and that makes token for me  but prefilling the above list does not work.
I'm using the 2.0.7 version.

Let me know the solutions for pre filling the token in completionView.

Thanks

**Comment by mgod** [comment]
Setting the adapter just sets the list of items in the drop down, it doesn't pre-fill anything in the view. To pre-fill the view, you need to use ```addObject```
