### ISSUE TITLE
ndroid.widget.ListAdapter.getCount()' on a null object reference com.tokenautocomplete.TokenCompleteTextView.performCompletion  Raw

### ISSUE THREAD

**Issue by gourav12** [splitwise/TokenAutoComplete#215]
Attempt to invoke interface method 'int android.widget.ListAdapter.getCount()' on a null object reference
com.tokenautocomplete.TokenCompleteTextView.performCompletion (TokenCompleteTextView.java:281)
com.tokenautocomplete.TokenCompleteTextView.handleDone (TokenCompleteTextView.java:312)
android.widget.TextView.onEditorAction (TextView.java:4483)

**Comment by gourav12** [comment]
Hi Marshall Weir,
i am getting sometime above issue.please tell me what is root cause of it.

**Comment by mgod** [comment]
It looks like you're not setting an adapter for the drop down for the token complete text view.
