### ISSUE TITLE
TokenDeletionStyle.Remove

### ISSUE THREAD

**Issue by ashdavies** [splitwise/TokenAutoComplete#220]
It would be useful to be able to specify a deletion style that performs in the same way as `TokenCompleteTextView.TokenDeletionStyle.Clear` but also includes the most recently completed token which would normally follow partial completion rules.

**Comment by mgod** [comment]
Do you mean that you want all but the most recently completed token to use .Clear and have the most recently completed token get replace by the completion text for that token instead of being cleared? If you have not started typing anything new and hit the delete key immediately after completing a token and .Clear is set, this should happen on most platforms. I haven't figured out exactly which platforms work this way.

**Comment by ashdavies** [comment]
No I mean a blanket clear rule, all tokens react the same way including the most recently completed token

**Comment by mgod** [comment]
Ah, I see. So the underlying inconsistent behavior is something provided by the system library. I'm not sure where the behavior comes from, though I'd be happy to add a fix if it's not too much of a hack. I'd prefer not to add this to the library if it's likely to make it less stable.

**Comment by ashdavies** [comment]
Yes I agree that the trade off would not be worth it if it were to affect the stability, allowing the user to modify the last created token by not clearing the whole thing (in the case of a spelling error) makes sense, I've found the behaviour to be occasionally inconsistent and I think it makes sense to have a clear rule that affects everything the same way and define a combination rule differently.

**Comment by JM-Agrimap** [comment]
Could you tie into TokenSpanWatcher.onSpanRemoved() to clean up the autocomplete text?

**Comment by mgod** [comment]
After some time fussing with this behavior, it seems pretty clear that there's not a good way to make any of the token deletion behaviors work reliably, and the system behavior is highly dependent on keyboard implementation and OS version, so I'm unfortunately removing any behavior around specifying how deletion behavior works and marking these kinds of issues as won't fix.
