### ISSUE TITLE
Keyboard not to go down when a token is added

### ISSUE THREAD

**Issue by Sandrichka22** [splitwise/TokenAutoComplete#221]
I want to implement a behaviour when the keyboard does not go down every time the user presses done and adds a token in the TokenAutoComplete view. How can I achieve this? I see that this is implemented in the library's handleDone method but I don't like this behaviour. I want the user to proceed writing and not needing to press the view over and over again to bring keyboard up
..

**Comment by nguyentando** [comment]
You can import the library code into your project and then change handleDone's behaviour.

**Comment by tihomirleka** [comment]
You can achieve this by setting custom `OnEditorActionListener` on `TokenAutoComplete`.

```
private TextView.OnEditorActionListener autocompleteOnEditorActionListener = new TextView.OnEditorActionListener() {
	@Override public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
		if (actionId == EditorInfo.IME_ACTION_DONE) {
			final TokenAutoComplete tac = (TokenAutoComplete) v;
				completionView.performCompletion();
				return true;
			}
		}

		return false;
	}


@Override protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
	setContentView(R.layout.my_activity);
	
	view.setOnEditorActionListener(autocompleteOnEditorActionListener);
}
```

**Comment by Sandrichka22** [comment]
Thanks for your reply @tihomirleka! I don't know how I've missed this. This works. Now I can continue writing without having to pull the keyboard up on every press on done.

**Comment by Sandrichka22** [comment]
And if someone wants to transfer the focus to another view, the second time the user presses DONE (first time to add the token, and second to transfer focus), I managed to do this with 
  
private TextView.OnEditorActionListener autocompleteOnEditorActionListener = new TextView.OnEditorActionListener() {

        @Override public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {

           if (actionId == EditorInfo.IME_ACTION_DONE) {

               String textEntered = completionView.getText().toString().replace(" ", "").replace(",", "");

                if (TextUtils.isEmpty(textEntered) && focusNext()) {
                    return true;
                }

                completionView.performCompletion();
                return true;
            }

            return false;
        }

    };
