### ISSUE TITLE
error: method setAdapter in class AutoCompleteTextView cannot be applied to given types

### ISSUE THREAD

**Issue by AbdelQuddous** [splitwise/TokenAutoComplete#223]
error: method setAdapter in class AutoCompleteTextView cannot be applied to given types;
required: T
found: CustomAdapter
reason: inferred type does not conform to upper bound(s)
inferred: CustomAdapter
upper bound(s): ListAdapter,Filterable
where T is a type-variable:
T extends ListAdapter,Filterable declared in method <T>setAdapter(T)

where CustomAdapter extends BaseAdapter

**Comment by mgod** [comment]
you must implement ListAdapter and Filterable on the adapter you set for the token view
