### ISSUE TITLE
How to Allow Typed Text ?

### ISSUE THREAD

**Issue by kirtan007** [splitwise/TokenAutoComplete#226]
first thanks for great library ,

I have created an Adapter with filterable interface which fetches items from REST API and displays it as suggestion.Everything work great till this point .What i want is allow user to enter typed text as well with auto completion ! it does not let me do it If I enter typed text and complete it with "," it takes suggestion Adapter's first item automatically instead of typed text. I am using this implementation in email client's TO field.
so I what i want is , user is allowed to use typed emails as well contacts from suggestions too.

Waiting for your reply.
Thanks.

**Comment by mgod** [comment]
You should be able to enter freeform text in version `3.0.0`. If you're just looking to allow users to hand-enter tokens, you should disable `performBestGuess` and make sure `defaultObject` returns a non-null value.
