### ISSUE TITLE
How to get autoComplete from any part of the typed String?

### ISSUE THREAD

**Issue by ashirvad358** [splitwise/TokenAutoComplete#227]
The search is based on initials of the required String. For example if the string to be searched is "B-243"
I have to type "B" to show the autoComplete. How to get the autoComplete dropDown if I type "43"??

**Comment by mgod** [comment]
The drop down will appear if the number of letters is >= the threshold and there are items in the adapter to show. My guess is that you need to change your filter function to make "B-243" match "43"
