### ISSUE TITLE
It is possible to input multiple split chars without text being tokenized with some keyboards

### ISSUE THREAD

**Issue by crezax** [splitwise/TokenAutoComplete#230]
I have added an example tokenizer to my app and made the comma my split char.
Then I just typed some characters, hit comma and... the comma just appeared! The keyboard I am using (TouchPal) added both comma and space (", ") when I tapped comma and subsequent comma clicks worked in similar fashion. Here is step by step what happened.

- Typing:
- "Example"
- tap comma
- "Example, "
- tap comma again
- "Example,, "

When I switched to Samsung keyboard, it worked as expected though.

- Typing:
- "Example"
- tap comma
- "[Example]"

**Comment by mgod** [comment]
This is the same issue as #184. I made the (incorrect) assumption that split characters would get entered 1 character at a time and need to update the infrastructure to be more generous in checking multi-character inputs from the keyboard.
