### ISSUE TITLE
How to populate Tokens in TokenCompleteTextView Progrmatically?

### ISSUE THREAD

**Issue by naveenkumarmallappa** [splitwise/TokenAutoComplete#233]
I need to show the already selected tokens in Edit screen. So I need to load the objects into TokenCompleteTextView  as dynamically. 
Can we do this?

**Comment by mgod** [comment]
There are some notes on this here: https://github.com/splitwise/TokenAutoComplete#programatically-add-and-remove-objects

**Comment by naveenkumarmallappa** [comment]
Thank you very much
