### ISSUE TITLE
Clear user input on onTokenAdded callback

### ISSUE THREAD

**Issue by Sandrichka22** [splitwise/TokenAutoComplete#235]
I have implemented the TokenAutoComplete text view in my project but I don't use the native FilteredArrayAdapter and list for showing filter suggestions, but I have my own list where I show the results from the filtering (I also have my own filtering method that does this for me). 

This works fine, but the only problem that I am having right now is when I click on an item of my list (and I call the addObject(token) method to actually add the token) I want to be able to delete the string that the user entered for the filtering since it is not needed any more. 

Is there a way to do this? Also I want to be able to delete the string although the user has, for example, already added 2 or 3 tokens.

Can someone help me? Thank you in advance. Hope I was clear of what I want to achieve.

**Comment by mgod** [comment]
I believe ```clearComposingText``` should do it? You might also look for examples of using ```AutoCompleteTextView``` with a custom list (this library is built on that core class, so the same code should work for managing the list yourself).

**Comment by Sandrichka22** [comment]
The `clearComposingText` method doesn't do anything, I already tried.

**Comment by mgod** [comment]
I think you'll have more luck trying to find examples of using the ```AutoCompleteTextView``` with a separate list instead of the drop down, but if you want to clear the text yourself, you'll need to get the current search text with ```currentCompletionText``` then find that text in the underlying editable (```Editable editable = getText();```) and use one of the ```Editable``` methods to remove the characters.

**Comment by cauli** [comment]
@Sandrichka22 

I know this is closed, but I've bumped into the same wall.
I wanted to delete the at sign `@`, an input by the user, after he selected an user from the list.

The main problem with Editable is that it was easy to mistakingly delete the new token view by replacing it.

Here's how I handled it.

```java
    @Override
    public void onTokenAdded(Object token) {

        Editable editable = this.getText();

        if (editable.toString().contains("@")) {
            int idx = editable.length()-1;

            while  ( idx >= 0 ) {
                if(editable.charAt(idx) == '@') {
                    editable.delete(idx,idx+1);
                }

                idx--;
            }
        }
    }
```
