### ISSUE TITLE
Tokens in one line are displayed too close to the tokens in the line above.

### ISSUE THREAD

**Issue by raylee4204** [splitwise/TokenAutoComplete#245]
As you insert tokens so they go over more than 2 lines of tokens, the additional tokens have no vertical space from the tokens above them.

The xml for the textview:

```
<?xml version="1.0" encoding="utf-8"?>
<TextView android:id="@+id/name"
          xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:background="@drawable/background_token"
          android:ellipsize="end"
          android:maxLines="1"
          android:padding="4dp"
          android:textColor="@android:color/white"
          android:textSize="14sp"
          tools:text="#francislata" />
```

And for the background drawable:

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <corners
        android:bottomLeftRadius="4dp"
        android:bottomRightRadius="4dp"
        android:topLeftRadius="4dp"
        android:topRightRadius="4dp" />

    <solid android:color="@color/orange" />
</shape>
```

![device-2016-08-11-122351](https://cloud.githubusercontent.com/assets/2085389/17596303/c9e2ce10-5fbe-11e6-99f8-220ff130fb3a.png)

**Comment by mgod** [comment]
Have you tried the ```margin``` property?

**Comment by raylee4204** [comment]
@mgod No I haven't. Where should `margin` property go?

**Comment by mgod** [comment]
@raylee4204 sorry, I meant use the standard ```android:margin``` property on the textview layout to specify more spacing around the view.

**Comment by raylee4204** [comment]
@mgod I tried using `marginTop` because it looks like there's no vertical space in between tokens, but it didn't change anything.

**Comment by raylee4204** [comment]
The problem, though, is that the vertical margin starts to disappear starting from the third line.

**Comment by mgod** [comment]
Hmmm, then I'm not sure how to fix it. I'd see if you can find any advice on TextView layouts with images.

**Comment by a-mehta** [comment]
`android:lineSpacingExtra` might be what you're looking for. I noticed that the spacing isn't uniform with the line that you're editing vs. the ones above.

**Comment by Leminity** [comment]
I found what the problem.

This issue's require to modify draw method in ViewSpan.class

'''
int padding = (bottom - top - view.getBottom()) / 2;
canvas.translate(x, bottom - view.getBottom() - padding);
'''

padding and tanslateY result is irregular.
After modifying the code will comment again.

**Comment by Leminity** [comment]
Test this code.

```
public void draw(Canvas canvas, CharSequence text, int start, int end, float x, int top, int y, int bottom, Paint paint) {
        //Centering the token looks like a better strategy that aligning the bottom
        final int paddingTop = 10;

        prepView();
        canvas.save();
        int tokenBottom = view.getBottom();

        canvas.translate(x, y + paddingTop - tokenBottom);
        view.draw(canvas);
        canvas.restore();
    }
```

and using lineSpacingExrta.

**Comment by viestursGr** [comment]
@Leminity Can you explain what ViewSpan.class you modified? New to Android.

**Comment by ayz4sci** [comment]
I had a similar problem, but the edit to ViewSpan class didn't work for me. So I did this instead, I placed the TextView inside another container and added the padding to the container:

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:padding="@dimen/space_3_dp">

    <TextView
        android:id="@+id/name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/tag_background"
        android:padding="3dp"
        android:text="Entertainment"
        android:textSize="12sp" />
</FrameLayout>

**Comment by vpdsouza** [comment]
@mgod Thanks for referring me here.  To answer your question, yes I have the vertical scroll bars in my xml but they do not work.  Here is the xml:  is anything wrong here that you see?

            <com.imbills.mobile.chat.ui.ChatRecipientView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/crvRecipients"
                android:textColor="@color/DarkestGray"
                android:imeOptions="actionDone"
                **android:scrollbars="vertical"**
                android:hint="@string/hint_enter_recipient"
                android:nextFocusDown="@+id/messageText"
                android:inputType="text|textNoSuggestions|textMultiLine"
                android:focusableInTouchMode="true"
                android:textSize="14sp"
                />

**Comment by MarcoGhaly** [comment]
You can wrap the TextView in a transparent layout and set padding for the layout

`<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:background="@android:color/transparent"
    android:padding="2dp">

    <TextView
        android:id="@+id/name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/background_token"
        android:ellipsize="end"
        android:maxLines="1"
        android:padding="4dp"
        android:textColor="@android:color/white"
        android:textSize="14sp"
        tools:text="#francislata" />

</FrameLayout>`
