### ISSUE TITLE
Focus Change

### ISSUE THREAD

**Issue by a-mehta** [splitwise/TokenAutoComplete#254]
Can you call `clearSections()` when focus changes from the TokenCompleteTextView (or make the function public)? 

For example, let's say there are multiple TokenCompleteTextViews with `TokenClickStyle.Select`. The first one has a few tokens, and one of the tokens is selected. Now, let's say that I change the focus to another TokenCompleteTextView. 

The current issue is that the previously mentioned token is still selected, as opposed to having the section cleared. The desired effect is to have the token to be unselected when focus is changed.

**Comment by mgod** [comment]
This makes sense. I don't have time to fix this at the moment, but I'd be happy to merge a PR with the call in ```onFocusChanged```.

**Comment by a-mehta** [comment]
https://github.com/splitwise/TokenAutoComplete/pull/256

**Comment by mgod** [comment]
2.0.8 should be available now and has this fix.
