### ISSUE TITLE
Dynamically add suggestions

### ISSUE THREAD

**Issue by wanaclem** [splitwise/TokenAutoComplete#255]
Nice work dude,So the issue is this instead of adding suggestions before hand I want to pull out suggestions from a remote database as the user starts typing...I tried implementing addTextChangeListener but its not working as expected for me...Please help.Thanks..I appreciate...

**Comment by mgod** [comment]
You have to build your own adapter if you want to be able to add suggestions on the fly, you can't use the ```FilteredArrayAdapter``` (see #74 and #93 for some more details). I'm not really sure how to do this myself.
