### ISSUE TITLE
addObject() at any position on text

### ISSUE THREAD

**Issue by rt90** [splitwise/TokenAutoComplete#257]
Is there a way to add object on defined position on text? By default, new object is added after prefix or after another object. So, is it possible to add object to any position on TokenCompleteTextView, eq:
To: abcd `email1@example.com` efgh
I want to add email1 between "abcd" and "efgh" text, but when i call addObject(item) the item is always added after prefix.

**Comment by mgod** [comment]
I don't think this is something we can add to the library at the moment. It's probably technically possible to make this happen, but there are a lot of places where we'd need to guarantee this behavior that are both complex and difficult to test.
