### ISSUE TITLE
Do not getting full Text written in multiautocompleteTextView

### ISSUE THREAD

**Issue by dipalikcspl** [splitwise/TokenAutoComplete#261]
I want to fetch whole text using this method:

Editable str = edtText.getEditableText();
but  above string can't getting full string.
 remove token and replace , with token in above method output.
please help me .or email on dipali@kcspl.co.in

**Comment by mgod** [comment]
This is unfortunately not something I intend to support with this library. It is possible for you to work around the issue (see #68 for example), but this behavior may change at any time.
