### ISSUE TITLE
setThreshold(1) not working for first token

### ISSUE THREAD

**Issue by arunsekaran02** [splitwise/TokenAutoComplete#264]
Suggestion drop-down not showing for first token's first character, after entering 2nd character only it appear. This only happens for first token only.

**Comment by PhungVanHoa** [comment]
In class TokenCompleteTextView, move code from afterTextChanged() of inner class TokenTextWatcher to onTextChanged();

**Comment by mgod** [comment]
I believe moving the code this way will break deletion on API < 19.

**Comment by nilayAcquire** [comment]
Still facing issue while setting up setThreshold(1) .  Tried above solution but no luck.
Can you please look into this?

**Comment by mgod** [comment]
@nilayAcquire the fix for this should be included in the `3.0.0-alpha2` version.
