### ISSUE TITLE
uncaught exception in performCollapse

### ISSUE THREAD

**Issue by savichris** [splitwise/TokenAutoComplete#267]
using version 2.0.8

 java.lang.IndexOutOfBoundsException: replace (4 ... 4) ends beyond length 3 at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1094) at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:500) at android.text.SpannableStringBuilder.insert(SpannableStringBuilder.java:220) at android.text.SpannableStringBuilder.insert(SpannableStringBuilder.java:34) at com.tokenautocomplete.TokenCompleteTextView.a(SourceFile:749) at com.tokenautocomplete.TokenCompleteTextView.b(SourceFile:1060) at com.tokenautocomplete.TokenCompleteTextView.a(SourceFile:55) at com.tokenautocomplete.TokenCompleteTextView$3.run(SourceFile:928) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:158) at android.app.ActivityThread.main(ActivityThread.java:7225) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by mgod** [comment]
I think I resolved this in `3.0.0`. Please let me know if you're still seeing the issue.
