### ISSUE TITLE
Not working in scrollview

### ISSUE THREAD

**Issue by Venkatesh2391** [splitwise/TokenAutoComplete#270]
For more than 1 line exists, then only able to see current line item, no able to see remaining line items
actullay i set it to wrap content even though its limited to one line, even i set collapse false but it working
this happening in scrolliew
![bug](https://cloud.githubusercontent.com/assets/10152091/21764033/01d37038-d687-11e6-9e00-0ee23188cfe8.png)

**Comment by mgod** [comment]
Sorry for the slow response! collapse only matters when the view no longer has focus. I think if you want it to keep showing tokens all in one line and show previous tokens, you'll need to put it in a horizontal scroll view and allow the width to wrap content. You'll probably also need to set singleLine to true.
