### ISSUE TITLE
Planning next version

### ISSUE THREAD

**Issue by mgod** [splitwise/TokenAutoComplete#272]
Hi everyone!

It's been a while since I've done significant work on this project and there are a number of bugs that have cropped up (#253, #242, #241, #238, #237, #228, #226, #220, #193, #184, #183, #172, #132, #95) that will require a lot of reworking. There are also some use cases I hadn't considered during my initial design that don't work well with the current structure. I'd also like to simplify and automate the testing process.

Part of this is that I'll be removing a lot of features and reducing the public interface of the class as much as possible. To help me figure out what I should keep and do better planning out improvements, please comment and let me know how you're using it. Here's the template I'd like to see. Please copy and paste this into a comment and complete it. See [my example](https://github.com/splitwise/TokenAutoComplete/issues/272#issuecomment-271924268) below.

```
### My use case (a few sentences describing it)

### Settings (choose the correct one in each [], first option is the default)

 - setDeletionStyle([Clear, PartialCompletion, ToString])
 - setTokenClickStyle([None, Delete, Select, SelectDeselect])
 - allowDuplicates([true, false])
 - performBestGuess([true, false])
 - allowCollapse([true, false])

### API (delete all functions you do not use directly)

 - setPrefix()
 - setSplitChar()
 - setTokenLimit()
 - setTokenizer()
 - setTokenListener()
 - getObjects()
 - addListeners()
 - removeListeners()
 - clearCompletionText()
 - currentCompletionText()
 - performCompletion()
 - performCollapse()
 - addObject()
 - removeObject()
 - clear()

### Behavior overrides (delete all functions you do not override)

 - performFiltering()
 - isTokenRemovable()
 - maxTextWidth()
 - enoughToFilter()
 - buildSpanForObject()
 - replaceText()
 - getSerializableObjects()
 - convertSerializableArrayToObjectArray()
 - canDeleteSelection()

### Workarounds (any customization that is likely to break if I stop subclassing MultiAutoCompleteTextView)


### Feature requests (anything you currently do that the library could do for you)
```

**Comment by mgod** [comment]
### My use case (a few sentences describing it)

We use the library to allow the user to select a list of people when creating an expense. We load data from the the Android contacts provider and a local database of existing Splitwise friends.

### Settings (choose the correct one in each [], first option is the default)

 - setDeletionStyle(Clear)
 - setTokenClickStyle(Select)
 - allowDuplicates(true)
 - performBestGuess(true)
 - allowCollapse(true)

### API (delete all functions you do not use directly)

 - setPrefix()
 - setTokenListener()
 - getObjects()
 - currentCompletionText()
 - addObject()
 - removeObject()

### Behavior overrides (delete all functions you do not override)

 - getSerializableObjects()
 - convertSerializableArrayToObjectArray()

### Workarounds (any customization that is likely to break if I stop subclassing MultiAutoCompleteTextView)

 1. We make the drop down appear the first time the view is visible even if there's no completion text.
 1. We add a text watcher the updates a separate view with the ```currentCompletionText()``` when the user types.

### Feature requests (anything you currently do that the library could do for you)

 1. I'd like it if the library let me style more of the view in the XML layout instead of in code
 1. Update the styles in the view to more closely match MD guidelines and use AppCompat views.

**Comment by raylee4204** [comment]
My use case (a few sentences describing it)

We use the library to allow the user to add hashtags to show their interests, and also select a list of people when sending them SMS messages. We load data from the API to pull suggested hashtags, and for SMS , from the Android contacts provider 

**Settings**

setDeletionStyle(Clear)
setTokenClickStyle(None)
allowDuplicates(false)
performBestGuess(false)
allowCollapse(false)

**API**

setTokenListener()
getObjects()
addObject()
removeObject()

**Comment by mgod** [comment]
@raylee4204 Thanks for the feedback! When you're getting the hashtags, is it just a list of hashtags or do you let the user enter other text as well like a Tweet editor?

**Comment by raylee4204** [comment]
@mgod I do accept regular texts along with hashtags.

**Comment by biovolt** [comment]
### My use case : 
I use TokenAutoComplete to autocomplete a list of areas in my app using my own adapter that fetches the data from the server
Thank you for your contribution

### Settings (choose the correct one in each [], first option is the default)

 - setDeletionStyle([Clear])
 - setTokenClickStyle([ Select])
 - allowDuplicates([false])
 - performBestGuess([true])
 - allowCollapse([false])

### API (delete all functions you do not use directly)
 - setAdapter
 - setSplitChar()
 - setTokenListener()
 - getObjects()
 - addListeners()
 - removeListeners()
 - clearCompletionText()
 - addObject()
 - removeObject()
 - clear()

### Behavior overrides (delete all functions you do not override)


### Workarounds (any customization that is likely to break if I stop subclassing MultiAutoCompleteTextView)
I am using our own class to create the tokens and swop the images to make it clear that they need to click to select and then delete

### Feature requests (anything you currently do that the library could do for you

I would like to add a remove image to the token and add an onclick to the image so that they can remove the token with 1 click
setTokenClickStyle() - > remove image

**Comment by riyase** [comment]
Hello.. i am using this library with a customAdapter. whenever i type something i am searching through db and populate my adapter. but the getText() method return text contains"," or ";".. so ihad to write my own function for getting the current typing text with help of "getSelectionStart()"
And another problem is when i click one of my item in customAdapter i am inserting an item using addObject(), this is working but there is no way to remove last entered key (typingText)

APIs 
getTypingText()
eg: ,, ,, ,, john peter  ->  John peter
addObject(Object object, boolean removeTypingText)

**Comment by riyase** [comment]
And also what if i want my keyboard to keep opened after done pressed on keyboard. is there any existing way to do this?

**Comment by mgod** [comment]
@riyase This isn't really the right place to have this conversation, so please open a new ticket if this doesn't answer your questions to continue the conversation.

If you're using your own adapter, you should just need to implement the ```Filterable``` interface to filter and load items from your database. If you've done this and haven't overridden any of the action handling components of the adapter, the library should manage things like providing the current text, selecting items and clearing content correctly through that interface for you.

If you're looking to provide your own custom view to show the list, please see #318

**Comment by mgod** [comment]
@biovolt Just to clarify for me, by "add a remove image" to the token, do you mean adding a separate area of the token that you can style that responds to selections differently than the main token body? I've been pretty hesitant to allow sub-token clicking both because it's hard and it feels like most tokens should be small enough that having separate click areas would be confusing for the user. I had intended TokenClickStyle.Delete for cases where you want to 1-click delete tokens as that felt like the more usable choice to me.

**Comment by biovolt** [comment]
Hi


I wanted to implement a x to remove the token  similar to what they do on the site below 


The double tap is too much effort. 😁




Look at the screen shot or go to www.property24.com and add areas 











On Sat, Jan 13, 2018 at 10:52 PM +0200, "Marshall Weir" <notifications@github.com> wrote:












@biovolt Just to clarify for me, by "add a remove image" to the token, do you mean adding a separate area of the token that you can style that responds to selections differently than the main token body? I've been pretty hesitant to allow sub-token clicking both because it's hard and it feels like most tokens should be small enough that having separate click areas would be confusing for the user. I had intended TokenClickStyle.Delete for cases where you want to 1-click delete tokens as that felt like the more usable choice to me.

**Comment by Danish1111** [comment]
1) Without picking any item from hint when i change focus it automatically add @example.com  
2)when i am click infront of selected item, automatically deleted the selected item without click on particular item

**Comment by mgod** [comment]
I've just deleted some comments because this isn't a help thread. If you're not commenting about what features you currently use in the library, please look for a different thread to post in or create a new one. I usually respond fairly quickly to new issues unless they 1) are the same as an existing open issue (though I try to point to the current issue in this case) or 2) do not provide enough context for me to understand what's being asekd.

**Comment by jrcacd** [comment]
When will be released the new version?

**Comment by mgod** [comment]
I don't have a timeline for the next version. There is a `3.0.0-alpha` version you can get with `implementation 'com.splitwise:tokenautocomplete:3.0.0-alpha@aar'` in your gradle dependencies, but I'm not quite done changing the interfaces I'm updating and there's no migration guide yet.

**Comment by jrcacd** [comment]
Thanks,

This is a must have library

**Comment by mgod** [comment]
There's a version `3.0.0-alpha2` available now. I don't expect the public interface to change at this point, but I'm still ironing out some edge case bugs.

**Comment by jrcacd** [comment]
Where's the **.allowDuplicates(false)** function?

**Comment by Krishnakantkhetan** [comment]
**Existing Bug**
If i add more than 100 email id's and performCollapse, the control gets stuck, it take a long time (more than 10 secs) to collapse.

**My use case :**
I use TokenAutoComplete to autocomplete a list of email id's copied from another source.

**Feature requests:**
I would like to have a paste option for bulk insertion at once. There should be addObjects() method to add bulk tokens.

**Comment by mgod** [comment]
`3.0.0` is available now and the docs should be up to date. I believe I've addressed most of the requests here (please let me know how the free form text support works for you if you need it!).

I've not added paste or bulk insert support. There's some ground work in place to make paste more reasonable to implement and `addObjectSync` should be much less resource intensive in a loop than the current `addObject` code.

I'm also not planning to support handling clicks on different pieces of the tokens. It's clear from looking at the underpinnings of the text layout that this problem is beyond the scope of what I can support in the library.
