### ISSUE TITLE
Suggestions does not show when android:hint is used

### ISSUE THREAD

**Issue by madsonic** [splitwise/TokenAutoComplete#275]
A easy workaround is to use `.setPrefix()` however the color for the prefix text could not be set.

**Comment by mgod** [comment]
You can set a styled ```CharSequence``` with a color in ```setPrefix()```. Things have been working fine with ```android:hint``` for me. Are you able to reproduce this with tweaking the example project in some version of Android?

**Comment by madsonic** [comment]
Maybe I was too quick to jump. I cannot seem to replicate it anymore. That is an awful lot of code to write to set the color. Perhaps it can be part of the next version and I can help you with that
