### ISSUE TITLE
Tokens with expandable views get cut off if last item

### ISSUE THREAD

**Issue by trevor-e** [splitwise/TokenAutoComplete#28]
Double clicking tokens to remove wasn't working out for me since it is really easy to trigger with normal horizontal scrolling behavior.  Instead I have made it so that if you click a token it will create a "close button" on the right which the user can then press to close.  When the button is revealed it pushes all tokens on its right over slightly to accommodate for its width.  If the token is deselected then the button becomes hidden again.  

Through much hacking and fighting with issues caused by nested clickable buttons (TokenImageSpan.onClick() does not play nice) I finally got a working version.  The only issue I've found is if the user has entered enough tokens to trigger horizontal scrolling (using singleLine), then they aren't able to click the last token's button.  The Button is created but pushed off the widget, and there's no space added to scroll over more to see it.  I can see the left edge of it if I enable the debug layout boundaries view, but still can't scroll to it.

I've tried invalidating the view to have it redraw everything but nothing seems to work.  Any idea?  Not sure if this bug is with the library or the android widget you extended.  If you have any suggestions on implementing a clean version of this I'd be all ears as well.  Right now it's very ugly and I have to compare the X value of the motion event to the button boundaries since I couldn't get the click to trigger otherwise.  Thanks.

**Comment by mgod** [comment]
I'm closing this because we changed the way overflow works. I'm not sure if it solves this problem completely, but it should help with it somewhat.

**Comment by gargamelius** [comment]
![c1](https://cloud.githubusercontent.com/assets/9364270/18743112/d81a41c4-80b7-11e6-801a-58032c3b2d61.gif)

The close button's visibility is set in setSelected
```
if (selected) {
  close.setVisibility(VISIBLE);
} else {
  close.setVisibility(GONE);
}
```

As you can see the blinking cursor remains stationary as if the size did not change.

Tested on Nexus 5x (7.0) and Galaxy S5 (6.0.1).

**Comment by mgod** [comment]
@gargamelius that looks like a different issue to me? From what I can see there, it looks like the cursor doesn't get properly invalidated on token selection. If you were to start typing with the incorrect cursor placement, does the text appear under the token or to the right of it as expected?

**Comment by gargamelius** [comment]
When typing, token becomes un-selected and shrinks so text appears as it should, however the behavior changes if there are two tokens. It appears to work better but I can get it to shift cursor positions erratically by tapping between tokens. Sometimes the cursor is pushed right by about the width of the close icon drawable.



I just started using the library and I might be doing something wrong.  I will have a look at the source code to better understand how this works.

**Comment by toidv** [comment]
I'm still getting this error, Do you have any update?
