### ISSUE TITLE
How can i get the filtered values ?

### ISSUE THREAD

**Issue by aamirmsw** [splitwise/TokenAutoComplete#284]

**Comment by mgod** [comment]
I'm not sure what you mean? ```getObjects()``` will return the objects that are in the view. Can you give me some more details on what you're trying to do?

**Comment by yogi9999999** [comment]
mObj[i] = new UserInfo(data.get(i).getName(),data.get(i).getEmail());
adapter = new Adapter(getApplicationContext(),R.layout.tokent_layout,mObj);
Here I am adding two values but I am getting only name on  onTokenAdded....not the email address

**Comment by mgod** [comment]
I'm still a bit confused here. `onTokenAdded` should be passing you a `UserInfo` object which will have the name and email you set for it. Am I missing something?
