### ISSUE TITLE
Is it possible to add a token without autocomplete? 

### ISSUE THREAD

**Issue by MatheusDinni** [splitwise/TokenAutoComplete#287]
for example write a word then press enter to add a token, or add a delimiter to make a token automatically.

**Comment by MatheusDinni** [comment]
The method setSplitChar() is supposed to do that, but it's not working. I'm using performBestGuess(false) and setSplitChar(' ') to allow user's free entry but nothing happens.

**Comment by mgod** [comment]
I think it should work if you set ```performBestGuess(true)``` and return a non-null value from ```defaultObject```.
