### ISSUE TITLE
Changing Text Color does not work

### ISSUE THREAD

**Issue by vpdsouza** [splitwise/TokenAutoComplete#288]
I am using this API in my chat app and the requirement is for newly added tokens, the text color must be blue indicating they can be removable.  But, one the message has been sent then those recipients who are already in the conversation cannot be removed.  Hence, that token must be disabled.  I am trying to achieve this by calling a method right after the message is sent with the following code but it doesn't do anything unfortunately...  Please help...

            TokenTextView tokenTextView = (TokenTextView) getViewForObject(chatUser);
            int color =  ContextCompat.getColor(getContext(), R.color.im_chat_grey);
            tokenTextView.setTextColor(color);
            tokenTextView.setEnabled(false);  //Since above code did not work, tried this too
            tokenTextView.invalidate();  //and tried this too but nothing is working

**Comment by mgod** [comment]
So `getViewForObject` is probably badly named. It should maybe be something like `createViewForObject`. You cannot reconfigure the view outside of the `getViewForObject` function as the library internals do not use the view directly and `getViewForObject` creates a new view every time it gets called - it doesn't return the exiting view  currently being displayed.

What you'll want to do is add a property to your object that says if it's removable or not. Then you'll want to call `invalidate` on the completion view to get it to re-draw all the tokens. When this happens, the view used internally by the library will be re-rendered to draw the token with the updated object data.
