### ISSUE TITLE
How can i temporarily fix the issuse #242 ??? 

### ISSUE THREAD

**Issue by duckm8795** [splitwise/TokenAutoComplete#291]
My deadline of the project i am working on is coming , I can't wait until next version of this library ( as you mentioned in issuse [#272](https://github.com/splitwise/TokenAutoComplete/issues/272)) .How can i temporarily fix issuse  [#242](https://github.com/splitwise/TokenAutoComplete/issues/242)  ?

**Comment by mgod** [comment]
Closed in #333.
