### ISSUE TITLE
TokenCompleteTextView get populated by first element of the set adapter want to avoid this

### ISSUE THREAD

**Issue by shagun-healthians** [splitwise/TokenAutoComplete#296]
TokenCompleteTextView get populated by first element of the set adapter want to avoid this. I want to show the options only when user types and then selected option is visible. If I change the content of the attached adapter then hint should appear, not the first element of the data set in adapter

**Comment by mgod** [comment]
I'm a little confused about what you're trying to do here, but you might just be looking for ```performBestGuess(false)```? Please feel free to re-open with more details if this isn't what you're looking for.
