### ISSUE TITLE
Delete Button inside the custom view of the contact chip is not receiving the onClick events

### ISSUE THREAD

**Issue by vijay559** [splitwise/TokenAutoComplete#297]
Thank you for providing this library. Its definitely sufficient for my needs. I have one use case which I couldn't get it to working. I created a custom contactChip and was returning for the getViewObject. In this customView, i have a delete button embedded in it. I know that you provided a TokenClickStyle.Delete. But I want the user to specifically click on the delete button inside the contact chip to delete that specific token. 

<?xml version="1.0" encoding="utf-8"?>
<com.example.ctrls.ContactChip 
xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@drawable/chip_bg"
    android:orientation="horizontal">

    <RelativeLayout
       // COntact Image goes here. 
    </RelativeLayout>

    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal">

        <TextView
            android:id="@+id/chip_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"
            android:textColor="@android:color/white"
            android:textStyle="bold" />

        <ImageButton
            android:id="@+id/chip_delete"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical|right"
            android:src="@drawable/chip_delete"
            />

    </LinearLayout>

</com.example.ctrls.ContactChip>

As you can see, I have the chip_delete button.  When I inflate this view, I set the onClickLIstener. But that never gets the click event. I am guessing it might be because the AutoCompleteTextView receives the onTouchEvent at the top level. I commented that code to see if that solves the issue, but still no luck. 

Any ideas for getting this to work?

**Comment by mgod** [comment]
This is not possible. If you want to make sure the user has a reasonable experience deleting tokens with a confirmation, look at ```TokenCompleteTextView.TokenClickStyle.Select``` and using the ```setSelected``` method in your view to display a different token to indicate that a second tap will delete the token.
