### ISSUE TITLE
Disable collapse in non-focus mode

### ISSUE THREAD

**Issue by sashwini** [splitwise/TokenAutoComplete#298]
I want to show a list of tokens in a text view feteched from API call. User is not allowed to add tokens from input. I added requestFocus = "false" to the layout of token text view but it collapses the tokens. I need the tokens list be in exapnded state always, even when it has no focus.

How can I do that?

**Comment by mgod** [comment]
```allowCollapse(false)```, though it you're not accepting any user input, I would strongly recommend using a ```RecyclerView``` with a ```StaggeredGridLayoutManager```. This library makes a lot of compromises to make handling input work reliably.
