### ISSUE TITLE
TokenDeleteStyle.Clear leaves undeletable characters behind after deleting token.

### ISSUE THREAD

**Issue by mdellavo** [splitwise/TokenAutoComplete#30]
Reproduction: type, select a completion, tap delete on softkeyboard a few times to delete characters.  Eventually you will be unable to delete any more characters leaving one or two behind.  

Leaving field and returning seems to allow you to delete the characters.

100% reproducible on Nexus 5 softkeyboard, unable to reproduce on emulator with emulated keyboard or softkeyboard.

Switching to TokenDeleteStyle._Parent seems to work around the problem

**Comment by mgod** [comment]
@mdellavo If you update to 1.3.0 are you still seeing this behavior?
