### ISSUE TITLE
Is there any way that I can long press on a token and show a popup?

### ISSUE THREAD

**Issue by awhlee** [splitwise/TokenAutoComplete#300]
Example would be a display name with a long press showing the underlying email address.
Thanks in advance.

**Comment by mgod** [comment]
I don't think so. The interactions the view supports are pretty limited due to the underlying implementation.

**Comment by awhlee** [comment]
I managed to get it working last night.  I wrote my own onTouchEvent() and used a GestureDetector to determine if the touch event was a long press.  Not too sure if this is the best way to do this but the behavior is what I was looking for.
