### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by khizar-lango** [splitwise/TokenAutoComplete#301]
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.tokenautocomplete.ContactsCompletionView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</RelativeLayout>

it should be updated to

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <your fully qualified name .ContactsCompletionView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

</RelativeLayout>

**Comment by mgod** [comment]
I probably won't make this specific change in the docs, but I'll try to remember to move the example to some other package name like com.example.ContactsCompletionView. Would that be clear enough?

**Comment by mgod** [comment]
Fixed.
