### ISSUE TITLE
How to have a onClick call inside a Token view 

### ISSUE THREAD

**Issue by SilvaCarlos** [splitwise/TokenAutoComplete#303]
Hi, I'm currently using TokenAutoComplete on a project. I was trying to add a button inside the Token's custom view, but the onClick call isn't being triggered when I click the button on the screen. Does anyone have any thoughts that might help?

**Comment by mgod** [comment]
Hi @SilvaCarlos! Unfortunately, due to the underlying implementation of the library, this isn't really possible. You can take a look at the discussion in #250 for more details.
