### ISSUE TITLE
TokenAutoComplete does not accept maxLines

### ISSUE THREAD

**Issue by thomasmbr** [splitwise/TokenAutoComplete#307]
Personally, I have trying to set up an "EmailCompletionView" that extends from "TokenCompleteTextView" so that it has a maximum of 1 line. When typed text becomes a token, it obeys the property maxLines = "1", but while I am typing text, it does a line break. It looks like Edittext is not being set to maxLines = "1". I may be wrong at some point, so I would like to ask your help on how I can make both the text being entered stay on just 1 line as to the tokens that have already been created in the TokenAutoComplete view.

`public class EmailCompletionView extends TokenCompleteTextView<EmailUserAvaiable> {

    public EmailCompletionView(Context context, AttributeSet attrs) {
        super(context, attrs);
        allowDuplicates(false);
        setTokenClickStyle(TokenCompleteTextView.TokenClickStyle.Delete);
    }

    @Override
    protected View getViewForObject(EmailUserAvaiable person) {
        LayoutInflater l = (LayoutInflater) getContext().getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
        TextView view = (TextView) l.inflate(R.layout.contact_token, (ViewGroup) getParent(), false);
        view.setText(person.getEmail());
        return view;
    }

    @Override
    protected EmailUserAvaiable defaultObject(String completionText) {
        return null;
    }

}`

`<br.com.custom.EmailCompletionView
                android:id="@+id/ccv_email"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="8"
                android:inputType="textEmailAddress"
                android:layout_gravity="center_vertical"
                android:ems="10"
                android:maxLines="1"
                android:imeOptions="actionNext"
                android:hint="@string/text_view_email"
                android:layout_marginStart="@dimen/item_layout_new_student"
                android:layout_marginEnd="@dimen/item_layout_new_student_expandable"
                />`

**Comment by mgod** [comment]
Thanks for the report!

I'm able to get the view to stay one line high in the example, even when lots of tokens have been added. Are you having trouble where the view is resizing even though you have ```maxLines``` set to 1? While you are entering tokens, the view may scroll tokens invisibly off the top of the text entry view allowing for multiple lines of tokens. If you're trying to force the view to keep the text and token on the same line see the workaround in the first comment on #37.
