### ISSUE TITLE
Use it in comment writing

### ISSUE THREAD

**Issue by harshitlalpura** [splitwise/TokenAutoComplete#309]
Hello I want to use this as for comment writing and taging username handles like twitter how do achieve that using this library ?

**Comment by mgod** [comment]
In theory you can make your own tokenizer that recognizes "#" as the beginning of a token and " " as the end and call ```performBestGuess(false)``` on your token field, which should allow entry of text along side tokens. You'll probably also need to change the split characters for the view.

However, I've been finding this behavior hard to work with and pretty unreliable and am likely to remove it from the next version of this library.
