### ISSUE TITLE
Partial text not getting reset

### ISSUE THREAD

**Issue by debjitk** [splitwise/TokenAutoComplete#318]
I am not using TokenAutoComplete autocomplete but a separate list view to filter data based on input by overloading "afterTextChanged". On clicking an item on the list view i am adding the item using "addObject" of TokenAutoComplete. But the previous partial text remains. How do I reset it to empty string ?

**Comment by mgod** [comment]
The underlying implementation is based on the ```AutoCompleteTextView``` and I know you can override the default drop down list with your own list (though I've never done it). I would look into doing this rather than trying to emulate the completion behavior like this.
