### ISSUE TITLE
onTokenAdded event does not fire when text is provided through espresso

### ISSUE THREAD

**Issue by BogdanLivadariu** [splitwise/TokenAutoComplete#319]
I'm working on creating UI tests for an app that uses this library
The framework I use for UI tests is `espresso 3.0`
seems like `onTokenAdded` from `TokenCompleteTextView.TokenListener` does not get triggered when text is provided by espresso framework.

Any clues how we can bypass/fix this ?

**Comment by mgod** [comment]
It's probably an issue with threading. I was pretty lazy about handling main thread vs background thread in some of the callback code. Any chance you can post your test case here?
