### ISSUE TITLE
getViewForObject does not support ViewHolder pattern

### ISSUE THREAD

**Issue by bigsquirrel** [splitwise/TokenAutoComplete#323]
It seems always use the last item view.

**Comment by mgod** [comment]
I'm a bit confused here – it definitely does not support the ```ViewHolder``` pattern (I'm considering changing the API to make it clear that it doesn't even really use the ```View``` except for layout), but why would you use the ViewHolder pattern in this case? It doesn't re-use the views, which is usually why you would use a ```ViewHolder```. Can you give me some insight into your use-case?
