### ISSUE TITLE
How to get the series of tokens as a string  instead of getting a single Token at a time

### ISSUE THREAD

**Issue by Kapil-Bhattarai** [splitwise/TokenAutoComplete#327]
I am trying to implement friend mentioning functionality in comment section using this library. So far, everything is working fine . This is how it looks like

![screenshot_20170924-142910](https://user-images.githubusercontent.com/21140766/30780951-f75a98f0-a135-11e7-9634-43460688dc34.png)

but when I click send button, I am getting result like this,

![screenshot_20170924-143107](https://user-images.githubusercontent.com/21140766/30780989-db032bb2-a136-11e7-9f97-20f715f07314.png)

I know, we can use onTokenAdded() method to get the individual tokens, but I am having problem to merge all the tokens and get the desired result like this

![img_20170924_145020](https://user-images.githubusercontent.com/21140766/30781049-df38284e-a137-11e7-8e84-25953b37d549.jpg)

Is there any support in library, so that we can achieve this ?

And, one more problem that I am facing is that, whenever user click comma ( , ) ,  a new token is generated based on what user has typed. Is there any way to get rid of this new token after clicking comma ? :)

**Comment by mgod** [comment]
There's no library support at the moment for getting the stringified contents out directly. You'll need to get the text, then replace each ,, with the text for the corresponding token from ```getObjects```  (they'll be in the same order).

for the , completion issue, I'm not sure there's a great solution at the moment. If you return ```null``` from ```defaultObject```, calling ```performBestGuess(false)``` and ```setSplitChar(' ')``` should in theory get everything working, but I've not felt like the current library support for mixed text and token input is very good. If you do find a good working solution for this generally, please follow-up here so I can look into making this use case work better.

**Comment by mgod** [comment]
Please see the free form text support in version 3.0.0. It's still a little experimental, but it should resolve both of these issues.
