### ISSUE TITLE
How to re-setTokenListener after remove it

### ISSUE THREAD

**Issue by ahmaadyunus** [splitwise/TokenAutoComplete#330]
I have implement TokenAutoComplete on my recyclerview . i want to remove the token listener and I set tokenlistener = null (remove listener)

on next some line after execute any process. the listener I wil set again but that function no working. please help :)
thanks

**Comment by mgod** [comment]
Generally, you should only set the token listener once and not change it. Can you give me some more overview on what you're doing? It sounds like maybe you're setting a separate token listener for each view in your list which won't work. Setting one listener, then removing that one listener and later setting a new one should work ok. It might also be that you are expecting it to be synchronous, which is not true. The token gets added in a separate thread asynchronously, then the listener is called in the main thread when the work is done.

**Comment by ahmaadyunus** [comment]
in my case, tokenautocomplete (tac) I use is in the recyclerview and each recyclerview item has a tac. if I already have a token on tac item index 0 and I add the recycler item, when notifydatasetchange is executed. the token on the item index 0 will disappear or move to another item.

flow that I want. when item bind view then listener must be removed and set back after all executed code to avoid duplication or bug when i notifydeteted.

because on my apps. when adding token the token should be stored in the List and when deleted it must be deleted from the list which in the end all data I will get nested like:

`{

    "dataList":[
        {
            "item":[
                {
                    "token":"a"
                },
                {
                    "token":"b"
                }
            ]
        },
        {
            "item":[
                {
                    "token":"a"
                },
                {
                    "token":"b"
                }
            ]
        }
    ]

}`
