### ISSUE TITLE
multiline input field with numeric keyboard

### ISSUE THREAD

**Issue by qstuff** [splitwise/TokenAutoComplete#336]
Hi,

I want to have a multiline input field with a numeric keyboard, so i used the following 
settings:

`
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:inputType="number|textMultiLine"
                android:maxLines="3"
                android:singleLine="false"
                android:focusable="true"
`

But this does not work. Only a single line is shown by the input field.
After the linewrap the previous line moves out on top.
When i change the inputType to "textMultiLine" the multiline works but i have the
alphanumeric keyboard.

Appreciate any suggestions on this

**Comment by mgod** [comment]
This appears to be an Android issue with `EditText` in general and not an issue specific to this library, so I'm going to go ahead and close this issue, but some searching on StackOverflow suggests using the following in your XML:

```
android:inputType="textMultiLine|number"
android:digits="0,1,2,3,4,5,6,7,8,9"
```

**Comment by qstuff** [comment]
Thanks for your answer. I already tried out what you mentioned above, without success.
So i tried my luck here.
Ok for me closing the case.

**Comment by mgod** [comment]
One thing worth noting - the view has some default settings for `inputType` that get set during initialization, so you might find that you need to set the `inputType` explicitly in code after the WML has finished inflating to get it to work correctly.
