### ISSUE TITLE
Changing focus on view.

### ISSUE THREAD

**Issue by sanjogshrestha** [splitwise/TokenAutoComplete#337]
I have a scenario. Let's say I have two token completion view. For first, if i search some values, it shows the data as auto complete suggestion. This is working fine. But if I do not select any suggestion and click my second completion view, the first completion view automatically adds the first suggestion as a object.

Is there any way we can prevent this? I don't want it to be pre-filled with user's selection.

**Comment by mgod** [comment]
I think you want `performBestGuess(false)`, but this might have some unintended consequences.

**Comment by sanjogshrestha** [comment]
performBestGuess(false) is not working for me.

**Comment by mgod** [comment]
Hmmm, you may also need to return `null` from `defaultObject`.
