### ISSUE TITLE
OnClickListener on MyCompletionView is not called

### ISSUE THREAD

**Issue by AhmadKabi** [splitwise/TokenAutoComplete#341]
Hi mgod. I am very sorry that I face another issue here.
I have set OnClickListener to MyCompletionView, all just work properly. I put MyCompletionView inside fragment. But when another fragment comes into the screen then I go back to the former fragment containing the view (MyCompletionView), the listener (OnClickListener) does not work. I set this listener on fragment's onStart() callback too.

any suggestion for this issue?
thanks for your great library

**Comment by mgod** [comment]
That sounds like it should work correctly. What are you using the `OnClickListener` to do?

**Comment by AhmadKabi** [comment]
for showing dropdown. I intend to use it like a Spinner use

**Comment by mgod** [comment]
Have you set a breakpoint in the `OnClickListener` to confirm that it doesn't get called? I would guess that your problem is more likely related to the drop down getting dismissed automagically at some point.
