### ISSUE TITLE
SwiftKey Keyboard handling breaks in TokenCompleteTextView, during replaceText()

### ISSUE THREAD

**Issue by markcapella** [splitwise/TokenAutoComplete#343]
I'd noticed and addressed an issue with my favorite eMail's Keyboard handling (k9mail / SwiftKey) and it looks like the error is introduced in your library that they build on, so while I've posted a fix over there, I'll chase it upstream and post it here too.

Linking to their issue might be faster for your quick review [0], I can post more if you need.

Also, Tl;DR; Screenrecord the bug in action: [1]

[0] https://github.com/k9mail/k-9/issues/3257
[1] https://www.dropbox.com/s/4mtyhzxdjzsb6gi/fix%20IMM%20issue.mp4?dl=0

**Comment by mgod** [comment]
Thanks for the feedback and the link to the PR. I do have a fix I've been working on for this, but your solution looks like it might be a lot simpler than what I was working on.

**Comment by mgod** [comment]
Version 3.0.0 includes a fix for this.
