### ISSUE TITLE
Remove last token with `TokenDeleteStyle.Clear`

### ISSUE THREAD

**Issue by NikolayKul** [splitwise/TokenAutoComplete#344]
From the docs:
> TokenCompleteTextView.TokenDeleteStyle.Clear
> 
> This is the default. The most recently completed token will turn into the partial completion text it replaces, all other tokens will just disappear when deleted

How can remove the last token instead of replacing it with a completion text?

**Comment by mgod** [comment]
It is unfortunately not possible to control this. It's also an unreliable behavior as it depends on the underlying keyboard implementation.
