### ISSUE TITLE
Autocomplete view loses foces and performs completion on Android 8.1

### ISSUE THREAD

**Issue by lewiemortier** [splitwise/TokenAutoComplete#348]
# Describing the issue

When the user starts typing, a list of autocomplete results is displayed under the EditText. The moment the user starts to type a single character that doesn't match a possible autocomplete result, the autocomplete results disappear. After the user taps yet another character, the `performCompletion()` method is called and focus goes to the next `EditText`.

# Configuration

- `allowDuplicates(false);`
- `setThreshold(2);`
- `performBestGuess(false);`
- `setDeletionStyle(TokenDeleteStyle.PartialCompletion)`
- `allowCollapse(false);`
- `setSplitChar(new char[]{',', ';', ' '});`

# Extra information
Only reproducable so far on (don't have any more devices to test this on)
- Nexus 5X, Android 8.1.0
- Google Pixel C, Android 8.1.0
- Library version: 2.0.8

See this video for more details: https://streamable.com/a382k

**Comment by mgod** [comment]
I've significantly re-worked a lot of the completion code in 3.0.0. I'm not sure if it will resolve this issue, but please try it and let me know if it does.
