### ISSUE TITLE
Perform completion gives a wrong token at times

### ISSUE THREAD

**Issue by shardullavekar** [splitwise/TokenAutoComplete#35]
I try to add token using performComplition if the given text is a valid email Id.
Here is the code I use:
ContactsCompletionView mToField;
isValidEmail(mToField.getText().toString().substring(4)) {
 mToField.performCompletion();
}
Many times I get a token for the first contact in my contact list. Why is that?

For example, I start typing aa@gmail.com – this id doesn’t exist in my contact list. when I call performcompletion – it adds aalok@gmail.com – which is the first record in my contact list. No idea why is this happening.

**Comment by mgod** [comment]
You can now turn off guessing with ```performBestGuess(false)```
