### ISSUE TITLE
space to create new labels without a list

### ISSUE THREAD

**Issue by chaostools** [splitwise/TokenAutoComplete#352]
I read the Readme and understood that it uses a list of already present data which will be shown while the user is typing .
What my requirement is  an edittext, in which a user is writing something and on pressing 'spacebar', his text should become a new tag. And on pressing the back button, it should delete such tag (no need for an attached list). Something like [this.](http://jsfiddle.net/abrhmcc/r6gar2c3/11/) (checkout the whitebox at bottom-right of the screen in desktop version of site) 

How can i achieve it with this library?

**Comment by mgod** [comment]
I think you can just set the threshold value to something really large, but you might find it more useful to just add a text watched to your edit text that detects spaces and tokenizes the values yourself.
