### ISSUE TITLE
Disable adding token without pressing dropdown

### ISSUE THREAD

**Issue by dragossusi** [splitwise/TokenAutoComplete#363]
I am populating the adapter using retrofit with observables.
I want to prevent adding tokens that are not in the adapter's list. Is it possible?

**Comment by mgod** [comment]
You should return `null` from `defaultObject` and leave `performBestGuess` to its default value of `true`.

**Comment by dragossusi** [comment]
Actually i want to disable bestquess too. I found a workaround overriding performCompletion


```
    override fun performCompletion() {
        if ((getAdapter() == null || getListSelection() == ListView.INVALID_POSITION) && enoughToFilter()) {
            //avoid adding
        } else super.performCompletion()
    }
```
