### ISSUE TITLE
Contacts completion view not clearing the token which is collapsed

### ISSUE THREAD

**Issue by maheshwariaanchal** [splitwise/TokenAutoComplete#365]
I am adding some tokens in contacts completion view by clicking on the data. Now I want to clear all the tokens in Contacts Completion View, So I am using the method 
mContactsCompletionView.clear(); to clear all the tokens.
But the tokens which are collapsed (Tokens in the form +2) or which shows the count are not getting cleared.
Please help me out. Thanks in advance.

**Comment by mgod** [comment]
This should be resolved in 3.0.0
