### ISSUE TITLE
onTokenRemoved fired multiple times when any token is removed or Completion text view is cleared

### ISSUE THREAD

**Issue by maheshwariaanchal** [splitwise/TokenAutoComplete#366]
I am removing tokens from contactsCompletionTextView. Whenever I remove tokens using clear() method the method onTokenRemoved of token listener is fired multiple times. 
Please Help. Thanks.

**Comment by mgod** [comment]
Please see #357. I am still working on the rewrite necessary to support fixing this. I do have an alpha version available (`3.0.0-alpha`), but it doesn't address this.

**Comment by maheshwariaanchal** [comment]
Thanks.

**Comment by mgod** [comment]
I believe this should be resolved in `3.0.0`.
