### ISSUE TITLE
Cursor resizes when a chip is added

### ISSUE THREAD

**Issue by hannayurkevich** [splitwise/TokenAutoComplete#375]
When box is empty the cursor has normal size:
![image](https://user-images.githubusercontent.com/13866048/50987132-c7aed400-1519-11e9-90c2-dea28aef9529.png)

But when any chip is added then it becomes huge:
![image](https://user-images.githubusercontent.com/13866048/50987163-e6ad6600-1519-11e9-937b-fd3576e5de61.png)

It looks weird, especially when you start typing text. 

Could you please fix it or give a clue how to fix it? Thanks!

**Comment by mgod** [comment]
I think this might do it: https://stackoverflow.com/questions/6225995/can-i-change-the-cursor-size-in-android-edit-text-field/15215378

I don't think there's a general way for me to handle this in the library more directly. Cursor sizing is buried pretty deep in the view.
