### ISSUE TITLE
Can't clear view text

### ISSUE THREAD

**Issue by IstrateAndrei** [splitwise/TokenAutoComplete#376]
I've added a `TextChangedListener` to my custom view in order to filter a list of objects when i type any text in the input field.
After I tap on one item from the filtered list I added to the view using `view.addObject(item)`.
After I successfully added an item, the `onTokenAdded(token: T)` method is called from within my `TokenCompleteTextView.TokenListener`.
I want to clear the text from the input field after an item was added but I get an IndexOutOfBoundsException

Any idea on how to do that?

**Comment by mgod** [comment]
You shouldn't need to manage the filtering or list display yourself. You'll need to provide a filterable `ListAdapter` and let the library handle showing the drop down. Can you give me some more details on what you need that the default behavior doesn't handle?

You might be able to resolve this with `clearCompletionText`.

**Comment by IstrateAndrei** [comment]
Thanks man, found the solution in [#163](https://github.com/splitwise/TokenAutoComplete/issues/163)
