### ISSUE TITLE
`CharacterTokenizer` constructor is package-private

### ISSUE THREAD

**Issue by chrimaeon** [splitwise/TokenAutoComplete#377]
Currently the `CharacterTokenizer` constructor is package-private making it not instantiatable by a custom view with different `splitChar` and `tokenTerminator` fields.

**Comment by mgod** [comment]
Whoops, that's a mistake. I'll fix it in the next version update.

**Comment by chrimaeon** [comment]
👍 Thank you!

**Comment by mgod** [comment]
Fixed in 3.0.0!
