### ISSUE TITLE
Single/First letter is not showing the suggestion list

### ISSUE THREAD

**Issue by mobiniuspabitraranjan** [splitwise/TokenAutoComplete#379]
Using the latest version 'com.splitwise:tokenautocomplete:3.0.0@aar' in my application and used this method .setThreshold(1) to allow the single/First letter to show the suggestion list.

But It is having some problem like
1. It is not allowing single letter to create token
2. it is not suggesting the suggestion list for first/single letter entered to the tokenise view.

can you reply the solution or make a new release with the fixes?
Thanks.

**Comment by mgod** [comment]
Thanks for the feedback! It looks like I failed to handle the case of 1 letter without a token terminator in the tokenizers. I should be able to fix this fairly quickly.

**Comment by mgod** [comment]
Fixed in `3.0.1`, which should be available shortly.

**Comment by mobiniuspabitraranjan** [comment]
Thanks @mgod for fixing this issue.
