### ISSUE TITLE
Resizable tokens do not seem to resize the parent view

### ISSUE THREAD

**Issue by gcgrant** [splitwise/TokenAutoComplete#384]
Hey;

I am trying to resize when of the tokens on click (to expand to show an X button). However this change does not seem to want to be reflected in the parent -- the text just ends up shrinking to accommodate the X button.

However if I put the exact same view outside of the TokenAutoComplete view, and try resizing it, it works fine. See attached screenshot.

Any ideas?

In the token view:
![image](https://user-images.githubusercontent.com/1373682/57402428-51f40580-71a5-11e9-8715-2f1449f157c7.png)
![image](https://user-images.githubusercontent.com/1373682/57402435-57e9e680-71a5-11e9-89c1-aebb86c1819a.png)

Outside the token view (chilling in a Frame Layout):
![image](https://user-images.githubusercontent.com/1373682/57402468-66d09900-71a5-11e9-83d9-b67e24798f20.png)
![image](https://user-images.githubusercontent.com/1373682/57402481-6b954d00-71a5-11e9-8d14-3a2f2dcd5fab.png)

**Comment by mgod** [comment]
If you call `invalidate()` on your token view after expanding one of the tokens, does it update to the wider size?
