### ISSUE TITLE
Token can not be edited 

### ISSUE THREAD

**Issue by AbanoubWagdyy** [splitwise/TokenAutoComplete#393]
Once i added the token inside my custom token field ,I can not edit it at all
I have only these options :
public enum TokenClickStyle {
        None(false), //...do nothing, but make sure the cursor is not in the token
        Delete(false),//...delete the token
        Select(true),//...select the token. A second click will delete it.
        SelectDeselect(true);
}

but how can i select the token and starting editing it

Thanks,

**Comment by mgod** [comment]
Unfortunately, there is no support for editing tokens. I do not expect this to be something that the library supports, though you can build your own system that removes the token, opens a view for the user to edit things, then re-adds the edited token again.
