### ISSUE TITLE
Is there any way to show tokens on the first line and show some tokens on 2nd line with count of remaining tokens

### ISSUE THREAD

**Issue by bijobaby-2009** [splitwise/TokenAutoComplete#396]
![img_20191120](https://user-images.githubusercontent.com/57980419/69216034-28bf2380-0b91-11ea-9b8b-def2d101d176.png)

**Comment by mgod** [comment]
I don't think so. The way it's currently implemented, the system that figures out how to put the count in doesn't have a way to deal with multiple lines of text and it would not be easy to add that functionality.

**Comment by bijobaby-2009** [comment]
Thanks for your reply . My problem is when I add a long text as token and add few small length tokens.  

![img_20191121](https://user-images.githubusercontent.com/57980419/69303212-1cdf6a00-0c42-11ea-9d28-e63c18548079.png)

![ipmsgclip_r_1574308915_0](https://user-images.githubusercontent.com/57980419/69303217-21a41e00-0c42-11ea-9ffe-0b46f8ae7960.png)


Only count is showing on the first line. When first token is a long text. Any solution is available for that?

**Comment by mgod** [comment]
You could set a `maxWidth` on your token that is small enough to allow a token and the `+2` to show up on the first line.

I'll also note that you might find it better to use `setPrefix("To")` on the token field rather than having a separate "To"  label depending on your layout needs.

**Comment by bijobaby-2009** [comment]
Thanks
