### ISSUE TITLE
After # and @ as you type first character, character and symbol both got deleted on Honor 7x phone

### ISSUE THREAD

**Issue by sahusarita15** [splitwise/TokenAutoComplete#398]
When the first character is entered after  "#" or "@",  The character along with "#" or "@" is getting cleared. Attaching a video demonstrating the same. The issue is also happening on Samsung s9+ 
[token_autocomplete.zip](https://github.com/splitwise/TokenAutoComplete/files/4002240/token_autocomplete.zip)

keyboards. Found the resolution here: https://github.com/splitwise/TokenAutoComplete/issues/51

However, the same solution is not working on Huawei Honor 7x device.

**Comment by mgod** [comment]
Can you try the hashtag editor in the example project on this device?
