### ISSUE TITLE
create tag with multiple words in one tag.

### ISSUE THREAD

**Issue by kaushal2406** [splitwise/TokenAutoComplete#402]
I want to tag with more than one word. i am looking for solution having multiple words in one tag .
can  any one help to find this type of solution . and i do not want to include seprater token character in tag . like remove "#" , "@" from token  tag displayed text.

**Comment by mgod** [comment]
You should be able to have multiple words in a tag. You can either not use " " as a token terminator or build your own `Tokenizer` class. A custom `Tokenizer` will also let you modify the contents of the token when it is detected.
