### ISSUE TITLE
How can I use it in jetpack compose?

### ISSUE THREAD

**Issue by virovinrom** [splitwise/TokenAutoComplete#448]
I'm currently migrate old java code to jetpack compose. Can I use your lib in Jetpack compose filed?

**Comment by mgod** [comment]
I'm not sure if this will work with compose. It has a number of set expectations about the view hierarchy it's installed in. That said, I would take a look at the [AndroidView](https://developer.android.com/jetpack/compose/migrate/interoperability-apis/views-in-compose) component and see if it works there. I will not be updating this library to be directly compatible with Jetpack compose.
