### ISSUE TITLE
Keyboard fails to come up when view is focused the first time

### ISSUE THREAD

**Issue by austynmahoney** [splitwise/TokenAutoComplete#48]
My `TokenAutoCompleteView` does not open the keyboard when it receives focus from a tap. The cursor shows up in the view, but the keyboard will only open if you tap inside it a second time. Has anyone else seen this issue and/or know how to resolve it?

I added an `OnFocusChangeListener` using  `myAutoCompleteView.setOnFocusChangeListener()` and it reports that the view receives focus, but still no keyboard.

**Comment by mgod** [comment]
This should be fixed in [1.3.0](https://github.com/splitwise/TokenAutoComplete/releases)
