### ISSUE TITLE
Showing an image loaded from the network in the token

### ISSUE THREAD

**Issue by arriolac** [splitwise/TokenAutoComplete#5]
What I would like to do is display an image right next to text as a token. This image is being loaded from the network but when I update the View I don't see the image reflected. I believe this is because a drawable is being created for the token View and thus cannot be updated.

**Comment by ssaxena01** [comment]
@arriolac @mgod  do you have some sample code on how you accomplished adding an image from the network to the token?

**Comment by arriolac** [comment]
@ssaxena01 it's been a while since I've touched this code but it was fairly simple. I was using Volley's `NetworkImageView` to retrieve the image over the network and the token view simply contained a `NetworkImageView`. Hope this helps. https://gist.github.com/arriolac/c68e3699f6a370dc9343

**Comment by ssaxena01** [comment]
@arriolac Thanks. My approach is similar with the exception of using Picasso library to load network images. But for some reason Picasso doesn't seem to load the url while it places the placeholder image without problem into the image view.

      protected View getViewForObject(User user) {
          LayoutInflater l =      
             (LayoutInflater)getContext().getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
              RelativeLayout view = (RelativeLayout)l.inflate(R.layout.recipient_token, (ViewGroup)
            DelayAutoCompleteTextView.this.getParent(), false);
    TextView nameView = ((TextView)view.findViewById(R.id.token_name));
    nameView.setText(user.getFullName());
    ImageView tokenImageView = (ImageView)view.findViewById(R.id.token_image);
    String url = user.getImageUrl();

    Picasso picasso = Picasso.with(context);
    picasso.setLoggingEnabled(true);
            picasso.load(url)
            .fit().centerCrop()
            .placeholder(R.drawable.default_avatar_image)
            .transform(new RoundTransformation(100, 2, false, context))
            .into(tokenImageView);
    return view;

    }

**Comment by arriolac** [comment]
It's possible that you may need to call `invalidate()` on the view after the image has been retrieved—I didn't run into this issue though.
