### ISSUE TITLE
Suggestions can't be seen.

### ISSUE THREAD

**Issue by dora-babu** [splitwise/TokenAutoComplete#55]
I have tried to use TokenCompleteTextView in a fragment dialog. As i entered more and more contacts the suggestions that appeared decreased and finally it disappeared and resulted in a crash. The LogCat's reason for the crash is : "OpenGLRenderer(6185):   GL_INVALID_VALUE". Maybe if you give support for maxLines, there can be workaround so that atleast a minimum number of suggestions will be visible always. I hope you guys will resolve this as early as possible.

**Comment by mgod** [comment]
Fixed in [version 1.3.0](https://github.com/splitwise/TokenAutoComplete/releases)
