### ISSUE TITLE
User Added Tokens Not In Adapter

### ISSUE THREAD

**Issue by Style87** [splitwise/TokenAutoComplete#61]
I'm using the tokens for hashtags. I have a preloaded FilteredArrayAdapter with a list of suggestions but I also want on the space key press to have whatever the user has typed in to be set as a token. Is there a way to create this functionality?

**Comment by mgod** [comment]
The tokenizing on space should be fixed in [1.3.0](https://github.com/splitwise/TokenAutoComplete/releases)
