### ISSUE TITLE
Possible to use Parcelable in place of Serializable?

### ISSUE THREAD

**Issue by Saketme** [splitwise/TokenAutoComplete#62]
I'm no expert in this field, but I keep reading how Parcelable is significantly faster than Serializable. 

Here's an example: http://prolificinteractive.com/blog/2014/07/18/why-we-love-parcelable/

Is it possible to Parcelable in this project instead?

**Comment by mediavrog** [comment]
too bad

**Comment by mgod** [comment]
@mediavrog I'm happy to consider using ```Parcelable``` if there's some concrete example of how much performance we're losing over it being simpler to set up or if there's some other reason to make the switch.

**Comment by mgod** [comment]
My read through of the performance tradeoff here suggests that probably in most use cases of the library, people are spending an extra 2-10ms on loading their models, which seems like not enough benefit given that you mostly won't even hit this code path.
