### ISSUE TITLE
Single line not working correctly

### ISSUE THREAD

**Issue by dlernatovich** [splitwise/TokenAutoComplete#63]
Hello. This is great library, but I have some problem, when I want that TockenView were singleLine. This issue looks like follows (screenshot). 
Can you help me to fix this? Thank you.
![bug](https://cloud.githubusercontent.com/assets/7397335/3662193/60a60912-11c8-11e4-9f65-e4093cc83b6a.png)

**Comment by mgod** [comment]
I'm guessing you're not happy with the way overflow gets handled? This should be fixed in [1.3.0](https://github.com/splitwise/TokenAutoComplete/releases)
