### ISSUE TITLE
Problems with 3.2.2 android version and 4.4.2

### ISSUE THREAD

**Issue by grmaciel** [splitwise/TokenAutoComplete#82]
Hi, first of all i would like to congratulate you on your library which is awesome, very extensible and pretty easy to use. I am facing some wierd behaviours though that i would like to see if it is a bug or what.

First of all running the api on android 3.2.2 it happens that its not breaking the line, it just adds tokens horizontally and you can scroll across the itens but i would like it to break the line as happens in other android versions. Is that a bug in the api or in the android version itself? The same happens after a change focus since it cant identify the proper lineVisibleEnd it doesnt add the +X text.

The problem that happens on android 4.4.2 is that after i change focus to another field and it adds the +X if i just click back on the AutoComplete field and then scroll my finger, the text scrolls horizontally and appears in the beginning of the field like a billboard panel :D

Do you have any sugestions on those behaviour?

Thank you.

**Comment by mgod** [comment]
This should be fixed in [1.3.0](https://github.com/splitwise/TokenAutoComplete/releases)
