### ISSUE TITLE
OnTokenRemoved() does not get called when pressing delete key on programmatically added Tokens

### ISSUE THREAD

**Issue by vinaysshenoy** [splitwise/TokenAutoComplete#83]
We don't use the Adapter component of the library. Instead, we have a custom FlowLayout which displays suggestions and we can tap on them to add them to the TextView.

The problem with this is, if we manually add a token to the TextView and use the delete(or backspace) key on the keyboard to delete them, the OnTokenRemoved() method of the listener is never getting triggered.

**Comment by mgod** [comment]
This should be fixed in [1.3.0](https://github.com/splitwise/TokenAutoComplete/releases), but I haven't been able to replicate, so please re-open if you're still seeing this.
