### ISSUE TITLE
Token isn't added when some text is replaced

### ISSUE THREAD

**Issue by Saketme** [splitwise/TokenAutoComplete#84]
Hello, I think I've found a bug. 

Description: When some text is replaced by a token, `TokenSpanWatcher's` `onSpanAdded()` doesn't always get called. This probably happens that text if pre-filled during the Activity's creation.

Steps to recreate this bug:
1. Pre-fill the field with some text like "ll"
2. Delete a character so that the suggestions come up.
3. Pick a token
4. The text ("l" in our case) gets replaced by a token and `replaceText(CharSequence)` is called. However, `TokenSpanWatcher's` `onSpanAdded()` doesn't get invoked.

Bug workaround:
Similar to what you've done in `addObject(Object, CharSequence)`, this does the trick:

    // Bug workaround: onSpanAdded isn't getting called
    if (!objects.contains(selectedObject)) {
           int offset = editable.length();
           spanWatcher.onSpanAdded(editable, tokenSpan, offset, offset + ssb.length() - 1);
    }

I'm on Android 5.0 Lollipop so I'm not sure if it's platform specific. Thank you.

**Comment by mgod** [comment]
I'm pretty sure this is fixed in 1.3.0
