### ISSUE TITLE
Extra comma is left when the last token is removed

### ISSUE THREAD

**Issue by AlexNab** [splitwise/TokenAutoComplete#85]
Hi, first of all I would like to say thanks for your great component. :-)

There is a small glitch with extra comma left when the last tag was removed. 
How to reproduce:

1. type several tags, e.g. 123, 456, 789 will give us `123` `456` `789`
2. remove each one of them
3. text field will not be empty as expected, but with a comma character left.

**Comment by vit001** [comment]
I can confirm this issue.

**Comment by mgod** [comment]
@vit001 I'm not able to reproduce the issue using the sample project. Are you able to get it to happen on a particular device/simulator/android version? I'm guessing this is extremely specific - like only happening on Samsung Galaxy Notes running 4.4.4 or something

**Comment by vit001** [comment]
It is happening for me on Samsung Galaxy S3 running Lollipop (Liquid Smooth ROM). I will try on simulator ...

**Comment by vit001** [comment]
I do not see this issue on my device with your sample project. Will investigate ...

**Comment by vit001** [comment]
@mgod - Confirmed that the issue happens in your sample app when the prefix is empty. When the prefix is non-empty the issue doesn't happen.

**Comment by mgod** [comment]
Awesome! I'm able to reproduce this now. As a quick fix, you can set the prefix to ```" "```, though this tweaks the layout in an annoying way

**Comment by vit001** [comment]
Thanks!
