### ISSUE TITLE
Project structure change

### ISSUE THREAD

**Issue by mgod** [splitwise/TokenAutoComplete#91]
@wdullaer looking over the project, it seems like the classes we could easily extract are:

```CharacterTokenizer
CountSpan
HintSpan
ViewSpan
TokenImageSpan (if we move TokenClickStyle as an internal enum)
SaveState
TokenInputConnection
```

I think the ```Tokenizer``` and the ```Span```s should definitely be moved out of the core file. I'm not sure it makes sense to extract the ```SaveState``` or the ```TokenInputConnection```. Does this sound good to you? Did I miss anything?

**Comment by wdullaer** [comment]
@mgod I think the `Span`s and the `Tokenizer` should definitely go into separate files.

The `Savedstate` logically belongs to `TokenCompleteTextView` so it makes sense to keep this as a private inner class.

I don't really know what the best approach is for the `TokenInputConnection` and maybe also the interface implementations `TokenSpanWatcher` and `TokenTextWatcher`. In less heavier code I'd implement their functionality as an anonymous inner class, or implement the interfaces on the parent class. However in this case it improves readability.
Splitting them off in separate files might remove them too far away: they don't make sense outside of the context of the `TokenCompleteTextView` (it would be rather hacky in the case of the interface implementations anyway)
I'm probably overthinking this now, so maybe we should keep these the way they are :-)

I'm going to be away from a computer for a week, so I'll be slower to reply.

**Comment by mgod** [comment]
@wdullaer I'm going to do this in the next week or so.
