### ISSUE TITLE
Support remote data sets

### ISSUE THREAD

**Issue by vincentjames501** [splitwise/TokenAutoComplete#92]
Loading data from a static set is often times unrealistic. In our case, we'd love to use this library but we need to be able to query a remote data set (as there could be tens of thousands of results and it's not realistic to prepopulate these items). Likewise, it would also be nice to support pagination remote data sets while scrolling.

**Comment by mgod** [comment]
This work just like it would for the default AutoCompleteTextView. Here's a good tutorial that should pretty much drop-in work with the TokenCompleteTextView https://developers.google.com/places/training/autocomplete-android

I'm thinking I might want to just add this as a sample at some point...
