### ISSUE TITLE
With getThreshold() set to 0, default object is added when view loses focus

### ISSUE THREAD

**Issue by vit001** [splitwise/TokenAutoComplete#94]
I would like to use a threshold of 0 in my app - a list of available tokens is always shown. However, since internally a space is added after every token, upon loss of focus the default object will be appended at the end. The sample app exhibits this behavior when the following is added to ContactsCompletionView:

@Override
public int getThreshold() {
return 0;
}

I think the solution is to modify enoughToFilter() to return false when getThreshold()==0;

**Comment by mgod** [comment]
hmmmm, modifying ```enoughToFilter``` like that would be a pain. How would you feel about requiring at least 2 characters for the focus loss completion to work? I haven't really found a solution for this that I like.

**Comment by vit001** [comment]
I am not sure I understand why modifying `enoughToFilter` is a bad idea. I was thinking of this:

    return end - start >= getThreshold()  &&  getThreshold() > 0

**Comment by mgod** [comment]
```enoughToFilter``` also gets used when the user hits done on the keyboard or types the split character, so making it permanently false for threshold 0 would disable them. I think I would be tempted to add a check in enough to filter to make sure ```end-start >= 1 && end - start > getThreshold()``` and see how that works

**Comment by wdullaer** [comment]
If you do not enable best guesses, the library tries to add an object with an empty string representation. 
I am specifically testing for that to get rid of this behaviour.
As a workaround you can try to ensure that the best guess for no input returns an object with an empty string representation `"".equals(defaultObject.toString()) == true`
