### ISSUE TITLE
TokenClickStyle can't be customised for "x" button to remove token

### ISSUE THREAD

**Issue by madhurtewani-wow** [splitwise/TokenAutoComplete#98]
It will be good if there is an option to customize TokenClickStyle.Delete to trigger only when clicked on "x" area (cancel / delete drawable) in the token instead of whole token.

**Comment by mgod** [comment]
I'm not sure I'm willing to include this in the core project. Most people will be using tokens small enough that limiting deletes to just a small area of the token will be a bad UX and I don't want to encourage that in the general case. If you're just looking for a way to prevent accidental deletes, try setting the token click style to ```Select```. I'd potentially consider other behavior changes or customizations if you can give me a better feel for your use case.
